[RB/Help] Added help file for instrument data entry
aces/Loris pull request #6902
Opened 2020-08-12 18:45 UTC by AlexandraLivadas

I added a markdown file under `modules/instruments/help/` so that Help instructions for the user will render when they are completing instrument data entry. Since the frontend points to the same file regardless of the instrument, the Markdown includes a general section about the data entry page as well as subsections for the individual instruments.

Here is a screenshot of how it renders in the frontend. 
<img width="1440" alt="Screen Shot 2020-08-12 at 2 43 56 PM" src="https://user-images.githubusercontent.com/35467361/90054749-447fd200-dcaa-11ea-9de6-ed01e57dc43f.png">

#### Testing instructions (if applicable)
1. Checkout this branch and go to the LORIS frontend.
2. Navigate to `Candidate`->`Access Profile` and choose any candidate with associated instruments.
3. Navigate to the Data Entry page for any of the timepoint's instruments.
4. Go to the top of the page and click on the `?`
5. View the markdown.

#### Link to related issue

* Resolves #5691

2020-08-12 20:22 UTC, AlexandraLivadas commented
@christinerogers I made a note in the PR description about how this resolves #5691. I will take another crack at adding Help text specifically for the BMI instrument later today!

2020-09-03 19:06 UTC, pierre-p-s approved these changes

2020-09-22 12:26 UTC, christinerogers requested changes
Hey @AlexandraLivadas  - looking at the purpose of this help text, 
I think this can be condensed and simplified greatly (something we started with Help text with Alex Knoll, written up in her Help text guide)  : 
* see my 3 major edits
* delete everything below that - I don't think the content for each sample instrument is distinct enough to warrant the extra scrolling / re-reading. 

Might you have time to do these easy changes this week?  let us know...

2020-10-06 13:37 UTC, christinerogers commented on modules/instruments/help/instruments.md
> +
```suggestion
# Instruments

```

2020-10-06 13:39 UTC, christinerogers commented on modules/instruments/help/instruments.md
> +Along with the Administration and Data Entry options, the sidebar for this instrument includes the option to specify the Validity of the instrument. If the Data Entry status is set to `Complete`, the
```suggestion
```

2020-10-06 13:40 UTC, christinerogers commented on modules/instruments/help/instruments.md
> +In the left sidebar panel (on tablets, click the list icon) - you can set status flags for this instrument form.  The Data Entry flag can only be set to Complete after the Administration and Validity
```suggestion
Status flags can be set in the left sidebar - the Data Entry flag can only be set to Complete after the Administration and Validity flags have been set. 
```

2020-10-06 13:46 UTC, christinerogers commented on modules/instruments/help/instruments.md
> +In the sidebar, the Data Entry status can be set to either `Complete` or `In Progress`. The status cannot be set to `Complete` if the Administration option is not set. If the Data Entry status is `In
```suggestion
The Data Entry flag can only be set to Complete after the Administration and Validity flags have been set.
While the Data Entry status is `In Progress`, you may see in the sidebar the option to delete all the instrument data which will clear all data in the form. 
```

2020-10-06 13:47 UTC, christinerogers commented on modules/instruments/help/instruments.md
> +If the instrument has multiple pages, the user must save the data individually for each page. If the user has navigated to a page that is not the `Top` page of the instrument, they will be unable to
```suggestion
```
removing

2020-10-06 13:49 UTC, christinerogers commented on modules/instruments/help/instruments.md
> +
```suggestion

```
remove extra space

2020-10-06 13:51 UTC, christinerogers commented
Looks like @AlexandraLivadas hasn't had time for this in the past few weeks. 
I committed directly the last changes requested.  

@driusan are you comfortable doing final review?

2020-10-06 13:51 UTC, christinerogers approved these changes

2020-10-06 13:52 UTC, christinerogers commented
@AlexandraLivadas if you have time still could you pull, update and re-post the screenshot, showing how the current text renders?  thanks!

2020-10-20 00:12 UTC, christinerogers commented
@driusan final review please

2020-11-12 13:38 UTC, driusan commented
this has not had travis run on it.

2020-11-17 21:52 UTC, laemtl commented
@driusan The only change is a new markdown file, so I don't see any reason for Travis to fail. I closed/reopen to see if that can help, and can investigate further if the status does not update.

2020-11-18 13:33 UTC, merged