[Tools] Enable PHPCS for data_integrity/fix_candidate_age.php
aces/Loris pull request #6918
Opened 2020-08-18 00:26 UTC by laemtl

2020-09-03 19:53 UTC, pierre-p-s commented
Looks like travis did not finish running for this PR somehow I dont really know why...

2020-09-10 15:12 UTC, driusan requested changes

2020-09-10 15:12 UTC, driusan commented on tools/data_integrity/fix_candidate_age.php
> +        echo "\t
This is changing the output (quite significantly)

2020-09-10 15:12 UTC, driusan commented on tools/data_integrity/fix_candidate_age.php
> +        echo "\t
Same

2020-09-10 15:12 UTC, driusan commented on tools/data_integrity/fix_candidate_age.php
> +            $inst for CommentID:$row[CommentID] could not be instantiated.
Same

2020-09-10 15:12 UTC, driusan commented on tools/data_integrity/fix_candidate_age.php
> +    Using the 'confirm' option will apply the necessary corrections to the data.
Same

2020-09-10 17:10 UTC, driusan approved these changes

2020-09-10 17:59 UTC, laemtl commented
@driusan  Ready

2020-10-30 19:00 UTC, merged