[BVL_feedback] Update testplan
aces/Loris pull request #7028
Opened 2020-09-14 12:32 UTC by haoweiqiu

## Brief summary of changes

- [x] Have you updated related documentation?

Updated BVL_feedback testplan.

2020-09-14 16:58 UTC, laemtl commented
Thanks @haoweiqiu, can you create an issue linked to this PR and publish it?

2020-09-14 19:00 UTC, laemtl approved these changes

2020-09-14 20:19 UTC, maltheism approved these changes

2020-09-28 20:42 UTC, christinerogers requested changes
some initial comments (see inline below) and typo found. 
Note how we describe elements consistently across loris documentation, e.g. menu (not a toolbar), pencil icon (not notepad) - important.

2020-09-28 20:42 UTC, christinerogers commented on modules/bvl_feedback/test/TestPlan.md
> + To find the Candiadate profile, first navigate to 'Access Profile', then select the specific Candidate profile from the list.
This edit is not necessarily unless you'd like to change it to tell the tester _where_ to look for feedback within each of these modules/pages (as with the pencil icon).  
It is very safe to assume that anyone testing Loris knows how to get to a candidate profile and instrument list page.  I see a few inaccuracies below, i'll correct as I go ...

2020-09-28 20:42 UTC, christinerogers commented on modules/bvl_feedback/test/TestPlan.md
> + A list of Intruments shall be found in this page as shown below.
```suggestion
 A list of Instruments is found in this page as shown below.  
```
typo and changing the tone - @haoweiqiu you'll notice we've basically banned "should" and especially "shall" from all our docs - that's a conscious decision for writing style.

2020-09-28 20:42 UTC, christinerogers commented on modules/bvl_feedback/test/TestPlan.md
> + To find an instrument, first navigate to a specific Candidate Profile, then click on a specific Visit Label.
```suggestion
Feedback on a whole Visit is accessed via the Instrument List page - click the pencil icon in the blue menu bar.
```
Important - for visit-level feedback, use the pencil icon while you're looking at the instrument list module (don't click through to a visit label)

2020-09-28 20:42 UTC, christinerogers commented on modules/bvl_feedback/test/TestPlan.md
> + *Note: The feedback button has the notepad icon in the toolbar as shown below.*
across loris 
```suggestion
 *Note: The feedback button is represented by the notepad icon in the menu as shown below.*  
```
* Menu (not toolbar)

2020-09-28 20:42 UTC, christinerogers commented on modules/bvl_feedback/test/TestPlan.md
> + *Note: The feedback button has the notepad icon in the toolbar as shown below.*
i think you should move this to the first line of your modifications - this pencil/notepad icon is the same trigger across multiple modules, not just in the instrument form

2020-11-27 19:58 UTC, christinerogers commented
Hi @haoweiqiu Could you address these soon?

2021-01-08 21:04 UTC, laemtl commented
@haoweiqiu Try to rebase to see if this helps passing the tests.

2021-06-01 00:39 UTC, christinerogers approved these changes

2021-06-01 00:40 UTC, christinerogers commented
This could be reviewed ahead of final merge, @driusan.

2021-07-08 18:04 UTC, ridz1208 commented
@cmadjar what's the discussion about ?

2021-07-13 13:58 UTC, cmadjar commented
@ridz1208 can you rebase?

2021-08-10 13:53 UTC, cmadjar commented
@driusan ready for you :)

2021-08-23 13:45 UTC, ridz1208 commented
@driusan why was discussion required re-added on this ?

2021-09-24 16:44 UTC, driusan requested changes
I don't think this test plan warrants including binary image files. Git is not a good place to track binary files, and they are not useful when reading the testplan outside of github. I don't see any of the usages here being really required.

2022-10-05 20:46 UTC, ridz1208 commented
Similar changes made causing conflicts

2022-10-05 20:46 UTC, closed without merging