[battery_manager] Fixing testing bugs
aces/Loris pull request #7044
Opened 2020-09-17 21:17 UTC by HenriRabalais

## Brief summary of changes

- [ ] Have you updated related documentation?

#### Testing instructions (if applicable)

1.

#### Link(s) to related issue(s)

* Resolves #6957
* Resolves #6958 
* Resolves #6955

2020-09-17 21:22 UTC, HenriRabalais commented on jsx/Modal.js
> +              onUserInput={submit}
This fixes one of the uncaught in promise errors

2020-09-17 21:23 UTC, HenriRabalais commented on modules/battery_manager/jsx/batteryManagerIndex.js
> +        this.setState({error: true}, reject);
removing unnecessary function calls.

2020-09-17 21:23 UTC, HenriRabalais commented on modules/battery_manager/jsx/batteryManagerIndex.js
> +    this.setState({add: false, edit: false, test: {}, errors: {}});
resetting errors upon form close so that they don't appear across forms.

2020-09-17 21:23 UTC, HenriRabalais commented on modules/battery_manager/jsx/batteryManagerIndex.js
> +        errors.ageMaxDays = 'Maximum age must be greater than minimum age.';
Adding form validation for age

2020-09-17 21:23 UTC, HenriRabalais commented on modules/battery_manager/jsx/batteryManagerIndex.js
> +        this.setState({errors}, reject);
removing unnecessary function calls.

2020-09-17 21:24 UTC, HenriRabalais commented on modules/battery_manager/jsx/batteryManagerIndex.js
> +        this.setState({errors}, () => resolve(test));
passing as function instead of calling function directly

2020-09-17 21:24 UTC, HenriRabalais commented on modules/battery_manager/php/testendpoint.class.inc
> +        }
Adding backend validation for the new validation added to the front end

2020-09-18 16:37 UTC, HenriRabalais commented on jsx/Modal.js
> +  onSubmit: PropTypes.func,
resolves the console warning about wrong prop type

2020-09-18 16:38 UTC, HenriRabalais commented on modules/battery_manager/php/testendpoint.class.inc
> +        }
Adds validation for instrument Order

2020-09-18 16:38 UTC, HenriRabalais commented on modules/battery_manager/jsx/batteryManagerIndex.js
> +          this.props.testEndpoint+(test.id || ''),
This was appearing as `undefined` in the network and was confusing. This resolves that issue.

2020-09-18 17:24 UTC, HenriRabalais commented on modules/battery_manager/jsx/batteryManagerIndex.js
> +          this.props.testEndpoint+(test.id || ''),
This was appearing as `undefined` in the network and was confusing. This resolves that issue.

2020-09-25 00:24 UTC, laemtl requested changes
Awesome work! The only thing I noticed is that there is still an error with testendpoint/ when submit the form with Instrument order > 127, but now it's a 400, not a 500.

2020-09-30 14:10 UTC, HenriRabalais commented
@laemtl I think a 400 error should be fine since that properly describes what's happening. Is the user receiver an error message indicating what made they submission a bad request?

2020-09-30 15:13 UTC, laemtl commented
Your point is valid. I think proper validation to avoid the propagation of the error is a better option, but as you said, the error also makes sense so it does not hurt much to live with it.

2020-09-30 15:16 UTC, laemtl approved these changes

2020-11-23 15:29 UTC, ridz1208 commented
@laemtl do you mind testing this PR ? (i see you approved it but no sign of manual testing)

@driusan It's ready for your review right after

2020-11-23 17:00 UTC, laemtl commented
@ridz1208 @driusan Ready for review.

2020-11-27 17:32 UTC, merged