[media] Update uploaded form TestPlan
aces/Loris pull request #7045
Opened 2020-09-18 14:44 UTC by haoweiqiu

## Brief summary of changes

- [x] Have you updated related documentation?

#### Link(s) to related issue(s)

* Resolves #6948  (Reference the issue this fixes, if any.)

2020-09-18 20:20 UTC, maltheism commented on modules/media/test/TestPlan.md
> +  1. Under **Browse** tab, a selection filter should be present on top of the page containing the following fields: File Name, Language, Project, File Visibility, PSCID, Instrument, Uploaded By, Visi
Hi @haoweiqiu, I think for filters `Site` exists.
![media_table](https://user-images.githubusercontent.com/16293415/93641733-c8745a80-f9ca-11ea-9056-aa2e391b486f.jpg)

2020-09-21 18:19 UTC, maltheism approved these changes

2020-09-21 21:08 UTC, christinerogers approved these changes
Hi Haowei - this looks good to me. 

In keeping with our conventions, could you add 1-2 lines at the top of your PR header so that it's clear

2020-09-24 19:59 UTC, HenriRabalais commented on modules/media/test/TestPlan.md
> +  3. Clicking on Upload tab should hide the data table and display a form with the following fields: PSCID, Visit Label, Instrument, Data of Administration, Comments, File to Upload
Data of Administration, or Date of Administration?

2020-09-24 20:00 UTC, HenriRabalais requested changes
Just a small correction, then looks good!

2020-10-19 22:45 UTC, christinerogers commented
@haoweiqiu  - could you address henri's comments this week?

2020-10-23 19:56 UTC, christinerogers commented
@driusan I think this could be final-reviewed for merge.

2020-10-30 19:04 UTC, merged