[MRI Violations] Add help text to MRI Resolved Violations
aces/Loris pull request #7077
Opened 2020-10-01 04:16 UTC by haoweiqiu

## Brief summary of changes

- [x] Have you updated related documentation?

#### Link(s) to related issue(s)

* Resolves #7021  (Reference the issue this fixes, if any.)

2020-10-02 14:44 UTC, laemtl commented
@christinerogers, @haoweiqiu I think a few lines on the Resolution Status can be useful.

2020-10-14 21:36 UTC, christinerogers requested changes
Hi @haoweiqiu  - Could you please post a screenshot in the PR description of how this help text looks when it is rendered in the front end?  see #6600 for an example. 
Verify as you do this that it renders in a user-friendly/readable manner, Thanks - 
One additional change requested below inline

2020-10-14 21:36 UTC, christinerogers commented on modules/mri_violations/help/resolved_violations.md
> +This page displays scans that have been resolved from MRI Violation. Use the Selection Filter section to narrow down your search in the data results table below.
Could take another pass at this first sentence? There's something that doesn't read smoothly in that last few words.

2020-10-19 22:40 UTC, christinerogers commented
hi @haoweiqiu  - would you have a moment this week to help us get this merged?  Should be a quick tweak on this PR.  Let me know - thanks

2020-10-19 22:57 UTC, haoweiqiu commented
@christinerogers Sure! I'll try to resolve this as soon as possible.

2020-10-23 19:47 UTC, christinerogers approved these changes
lgtm thanks

2020-10-30 19:12 UTC, merged