[DQT] solves saved queries having wrong operator in list.
aces/Loris pull request #7115
Opened 2020-11-05 20:57 UTC by maltheism

## Brief summary of changes

Solves saved queries having wrong operator in list.

#### Testing instructions (if applicable)

1. Visit DQT
2. Look at saved queries
3. The operator should be correct

2021-01-08 19:42 UTC, laemtl requested changes
Dismissed.

2021-01-12 03:52 UTC, laemtl approved these changes

2021-01-12 03:56 UTC, laemtl commented
Works great. I noticed the same issue in Define filters (operator is always AND). (#7287)

2021-01-13 12:58 UTC, maltheism commented
@laemtl oh I think that was fixed on cbigr but I forgot to make a PR here for it.

2021-01-25 14:57 UTC, merged