[publication] fix notification
aces/Loris pull request #7240
Opened 2020-12-17 02:07 UTC by kongtiaowang

## Brief summary of changes
add notification funtion for upload , review and submission.
#### Testing instructions (if applicable)
 upload , review or submit a proposal, then user who has the notification services will get the email.
#### Link(s) to related issue(s)
https://github.com/aces/Loris/issues/7204

2020-12-17 16:26 UTC, CamilleBeau commented
Failed test suite. Looks like it can all be fixed with phpcbf

2020-12-17 16:57 UTC, CamilleBeau commented
I tested this PR and it fixed the notification. I set permissions from publication to be received in my preferences, then I made a new account and uploaded a proposal & edited the proposal. I got notifications in both of these cases to my original account's email, but the notification implied that it was _my_ project proposal when I think it should refer to _a_ project proposal. 

Here are the messages received to the user that had notifications set. These messages seem like they are intended for the user who created the proposal.

> Hello,
> This is to confirm your project proposal "Testing a project" received on 2020-12-17.
> We will notify you once your proposal has been reviewed. In the mean time, you
> can edit your project proposal through the following link: /publication/view_project/?id=3.
> 
> Thank you,
> The ccna Team
> 

> Hello,
> Your project proposal "Testing a project" has been reviewed.
> You can view the details by clicking the following link /publication/view_project/?id=3.
> 
> Thank you,
> The ccna Team

2020-12-17 17:37 UTC, kongtiaowang commented
@CamilleBeau Good catch! I have fixed the template file. It should be used to all the registed users not only the owner. Could u review again?

2020-12-17 18:35 UTC, CamilleBeau commented
> @CamilleBeau Good catch! I have fixed the template file. It should be used to all the registed users not only the owner. Could u review again?

Looks good! Just need to fix for test suite again

2020-12-21 14:12 UTC, driusan requested changes

2020-12-21 14:12 UTC, driusan commented on smarty/templates/email/notifier_publication_review.tpl
> +This project proposal "{$Title}" has been reviewed.
This sentence is grammatically incorrect. It should be "The project proposal {$Title} has been reviewed." not "This"

2020-12-21 14:12 UTC, driusan commented on smarty/templates/email/notifier_publication_edit.tpl
> +This project proposal "{$Title}" has been edited by {$User}.
This is also grammatically incorrect.

2020-12-21 14:12 UTC, driusan commented on modules/publication/ajax/FileUpload.php
> +            $msg_data = [
This block looks like it's indented wrong.. it randomly goes up an indent level with no change in scope. I'm not sure why phpcs isn't flagging it.

2020-12-21 22:09 UTC, CamilleBeau approved these changes

2021-02-06 17:56 UTC, ridz1208 commented
@CamilleBeau can you please put the pass manual test flag if you have tested the PR ?

2021-02-06 18:08 UTC, ridz1208 approved these changes

2021-02-06 18:09 UTC, ridz1208 commented
@driusan in your hands

2021-02-08 14:09 UTC, merged