[filterable_datatable] Fix Query Param Filtering Bug
aces/Loris pull request #7245
Opened 2020-12-17 18:21 UTC by HenriRabalais

## Brief summary of changes

#### Testing instructions (if applicable)
1.

#### Link to related issue
* Resolves #7216

2020-12-18 16:09 UTC, ridz1208 commented
@HenriRabalais travis is still failing

2020-12-18 16:58 UTC, HenriRabalais commented
@ridz1208 Yes, I tried `make checkstatic` but everything seems to be working. I'm also not clearly interpreting the messages from travis, so I'm unsure how to proceed.

2020-12-18 17:02 UTC, ridz1208 commented
<img width="1680" alt="Screen Shot 2020-12-17 at 10 51 09 AM" src="https://user-images.githubusercontent.com/15268287/102640655-d2703b80-4128-11eb-8f8e-fc877b3ab6cd.png">

the error is the query selector (see image) its not a static error

2020-12-18 17:52 UTC, driusan commented
`make checkstatic` is passing on GitHub too.. it's the integration tests that are failing.

2020-12-18 19:26 UTC, kongtiaowang commented
@HenriRabalais I am looking into it. The integration test of media filter faild.

2020-12-18 21:10 UTC, kongtiaowang commented
There is a bug found by Integration Test.
File Name filter doesn't work, it always shows no results.
<img width="470" alt="屏幕快照 2020-12-18 下午3 48 58" src="https://user-images.githubusercontent.com/9876007/102661738-77037500-414b-11eb-9fbb-e3a6e79e0f4f.png">
![屏幕快照 2020-12-18 下午3 49 47](https://user-images.githubusercontent.com/9876007/102661742-7a96fc00-414b-11eb-85d5-24b592bad1df.png)

2020-12-18 21:33 UTC, HenriRabalais commented
Thanks @kongtiaowang !!

2021-01-06 23:50 UTC, HenriRabalais commented
@ridz1208 needs re-review

2021-01-08 20:55 UTC, laemtl requested changes
Works well for 1 filter, but not 2, where only the second is considered.

2021-01-12 19:49 UTC, HenriRabalais commented
> Works well for 1 filter, but not 2, where only the second is considered.

Could you provide a screenshot example?

2021-01-12 20:12 UTC, laemtl commented
@HenriRabalais

**Expected**
![Screenshot from 2021-01-12 15-10-35](https://user-images.githubusercontent.com/32041423/104367280-94c4bf80-54e8-11eb-8a45-2e55a7cf8256.png)

**Result**
![Screenshot from 2021-01-12 15-11-05](https://user-images.githubusercontent.com/32041423/104367277-942c2900-54e8-11eb-8367-9b1527d15030.png)

2021-01-19 15:28 UTC, HenriRabalais commented
@laemtl I'm not sure I understand, both of those filters look fine to me.

2021-01-19 20:55 UTC, HenriRabalais commented
@laemtl should be fixed now!

2021-01-20 19:54 UTC, laemtl commented
@HenriRabalais Awesome, the problem is fixed! I found another small issue: 
- if you visit the link below, you will notice that the subproject filter is ignored. 
/battery_manager/?visitLabel=V1&subproject=1&stage=Approval

![Screenshot from 2021-01-20 14-53-21](https://user-images.githubusercontent.com/32041423/105227438-5013d680-5b2f-11eb-806f-49d6b914aa6c.png)

The filters are correctly populated now, but the results contain 2 entries for the CIE subproject, which are not there when the filters are selected manually.

2021-02-06 18:11 UTC, ridz1208 commented
@HenriRabalais please fix when possible

2021-02-09 21:40 UTC, laemtl approved these changes

2021-02-11 14:45 UTC, merged