[Media] Distinguish between file and other fields missing.
aces/Loris pull request #7249
Opened 2020-12-18 19:06 UTC by xlecours

This is a proposed solution for https://github.com/aces/Loris/issues/7207

> uploading a big (>1024M) file and got an error message saying that there was an upload error. The message said that some of the required fields were missing even though I filled out the PSCID and VLabel.

This adds a specific error message for when the file can't be or is not uploaded.

2020-12-22 17:30 UTC, nicolasbrossard requested changes

2020-12-22 17:30 UTC, nicolasbrossard commented on modules/media/ajax/FileUpload.php
> +            "The uploaded file is missing. Pelase contact the administrator",
Pelase => Please

2020-12-22 17:31 UTC, nicolasbrossard commented
@xlecours This did not work on my VM. I still get a message telling me that I need to fill all fields, along with an HTTP 400 error inside the JS console. I only filled the PSCID and visit field, along with the file chooser.

2020-12-23 17:22 UTC, xlecours commented
`$_FILES` is an empty array when the upload fails so `!isset()` was returning false

2020-12-23 17:54 UTC, nicolasbrossard approved these changes
Works for me. I'd change the error message to "File could not be uploaded successfully. Please contact the administrator": I think the current message seems to indicate that the file field has not been filled out on the form.

2021-01-05 15:58 UTC, xlecours commented on modules/media/ajax/FileUpload.php
> +            "The uploaded file is missing. Please contact the administrator",
```suggestion
            "File could not be uploaded successfully. Please contact the administrator.",
```

2021-01-05 16:05 UTC, driusan commented
This is failing because of PHPCS

2021-01-06 14:28 UTC, xlecours commented
> This is failing because of PHPCS

Is the survey module PR merged?

2021-01-06 15:17 UTC, driusan commented
Which survey module PR?

2021-01-06 16:41 UTC, xlecours commented
@driusan The one that would fix:
```
FILE: ...work/Loris/Loris/modules/survey_accounts/php/addsurvey.class.inc
----------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
----------------------------------------------------------------------
 240 | ERROR | [x] Equals sign not aligned with surrounding
     |       |     assignments; expected 3 spaces but found 2 spaces
 241 | ERROR | [x] Equals sign not aligned with surrounding
     |       |     assignments; expected 2 spaces but found 1 space
----------------------------------------------------------------------
PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
```

2021-02-06 18:28 UTC, ridz1208 commented
@nicolasbrossard I added the pass manual tests flag because I assumed it was tested given your comment
@xlecours I fixed PHPCS

@driusan in your hands now

2021-02-08 14:06 UTC, merged