[libraries/BVL_Feedback_Panel] $sessionID must be type SessionID
aces/Loris pull request #7289
Opened 2021-01-18 15:16 UTC by maltheism

## Brief summary of changes

A string was given and this change resolves it.

2021-01-18 16:17 UTC, laemtl commented
There is another [getFeedbackPanel here](https://github.com/aces/Loris/blob/5166ada28fbb01ac020f03c6eb38766f2ff7e32a/php/libraries/NDB_BVL_Instrument.class.inc#L2415). I wonder if the 2 signature should agree, it will be confusing otherwise.

If so, the sessionID type change should be done before calling getFeedbackPanel.

2021-01-18 16:20 UTC, laemtl commented
Related to #7063

2021-01-20 20:13 UTC, laemtl commented
Just noticed the [signature](https://github.com/aces/Loris/blob/4af1256b6072ec79e08870dc1f44e851b343600d/modules/instrument_list/php/instrument_list.class.inc#L293), sessionID should be of type SessionID, so this function is probably called somewhere with the wrong argument. Maybe also specifying the types in the function definition will help to clarify the confusion.

2021-02-11 14:29 UTC, driusan commented
@maltheism Can you rebase so that this runs with php8 and to ensure all the latest phan fixes still pass?

2021-02-12 18:28 UTC, kongtiaowang approved these changes
LGTM

2021-02-12 18:51 UTC, laemtl requested changes

2021-02-12 18:51 UTC, laemtl commented on modules/instrument_list/php/instrument_list.class.inc
>      function getFeedbackPanel($candID, $sessionID): string
The signature (sessionID) disagrees with the current change.
This function is called somewhere with the wrong argument. Specifying the types in the function definition will help to clarify the confusion.

2021-02-12 19:36 UTC, laemtl commented
@maltheism I submitted a commit with suggested changes. Let me know what you think.
Also, I investigated I couldn't find an call of getFeedbackPanel with $sessionID of type string.

2021-02-12 19:47 UTC, driusan commented
Our tests aren't amazing at finding mismatches because `PhanTypeMismatchArgument` is still ignored. After #7322 I have another PR in the pipeline that fixes the remaining `PhanTypeMismatchArgument` errors and unignores it.

In the meantime, maybe adding `declare(strict_types=1);` to the file with the signature change would help the tests find any culprits calling it with a string?

2021-02-12 19:54 UTC, laemtl commented
@driusan I added declare(strict_types=1) and it confirms my suspicion: The code breaks when we call 
`new \SessionID($sessionID)` with ` PHP Fatal error:  Uncaught TypeError: Argument 1 passed to ValidatableIdentifier::__construct() must be of the type string, object given`.

2021-02-12 19:59 UTC, laemtl commented
Since the strict _types flag, Phan is complaining with 
` modules/instrument_list/php/instrument_list.class.inc:255 PhanTypeMismatchArgumentProbablyReal Argument 1 ($select_inactive_threads) is $feedback_select_inactive of type ?'Y' but \NDB_BVL_Feedback::getMaxThreadStatus() takes bool (no real type) defined at php/libraries/NDB_BVL_Feedback.class.inc:380 (the inferred real argument type has nothing in common with the parameter's phpdoc type)`

2021-02-12 20:12 UTC, driusan commented
That sounds a lot like one of the errors I had to fix while fixing the phan errors.

2021-02-12 20:16 UTC, laemtl commented
@driusan I tried something and it fixes phan.

2021-02-12 20:17 UTC, driusan commented
The 'Y' => true thing looks familiar. I think that's what I had to do to fix it too..

2021-02-15 17:47 UTC, laemtl approved these changes

2021-02-15 17:51 UTC, merged