[publication] Add columns to publications
aces/Loris pull request #7361
Opened 2021-03-01 17:24 UTC by pierre-p-s

## Brief summary of changes

- Added 3 data columns to the publication module:
        - Date published,
        - Journal,
        - link and
        - publishing status (dropdown menu with: in progress or published)

#### Testing instructions (if applicable)

1. In publication module, propose a project entering data in the new columns
2.  After the project is proposed, go into the browse tab and click on the project. Check that the new columns appear and that the data matches the one you just entered

#### Link(s) to related issue(s)

* Solves a CCNA issue: https://github.com/aces/CCNA/issues/4424

2021-03-02 14:54 UTC, kongtiaowang commented
rebase after https://github.com/aces/Loris/pull/7369

2021-03-02 15:01 UTC, pierre-p-s commented
> rebase after #7369

Thanks.

2021-03-10 15:37 UTC, kongtiaowang commented
The schema SQL file needs to be modified as well.
https://github.com/aces/Loris/blob/1abab548c10a553ec2d054fcf3ff887496dd0f36/SQL/0000-00-00-schema.sql#L2148

2021-03-10 19:54 UTC, pierre-p-s commented
> The schema SQL file and RB_file need to be modified as well.
> https://github.com/aces/Loris/blob/1abab548c10a553ec2d054fcf3ff887496dd0f36/SQL/0000-00-00-schema.sql#L2148

I rebased and added the changes to the schema. Not sure what I should do about the RB_Files

2021-03-10 20:47 UTC, driusan commented
This should be going to the main branch

2021-03-11 15:26 UTC, kongtiaowang commented
Please ignore the RB files. It doesn't change the schema.

2021-03-11 15:48 UTC, pierre-p-s commented
I cant seem to be able to run make dev on main dev. I am getting the error attached below. If someone knows how to fix it please let me know.

![Screen Shot 2021-03-11 at 10 39 45 AM](https://user-images.githubusercontent.com/57676906/110814240-41a48a00-8257-11eb-93f9-f626f7ddc2d3.png)

2021-03-17 15:23 UTC, kongtiaowang commented
@pierre-p-s try: "make clean" then "make dev", it may solve your issue. Good luck.

2021-03-17 16:03 UTC, pierre-p-s commented
> @pierre-p-s try: "make clean" then "make dev", it may solve your issue. Good luck.

It did not work for me

2021-03-17 16:30 UTC, ridz1208 commented
@pierre-p-s what versions of node and npm do you have ?

```
node -v
npm -v
```

2021-03-17 16:35 UTC, ridz1208 commented
> Do I need to update them?

I don't think so I have the same versions and it works for me

2021-03-19 19:54 UTC, driusan commented
have you tried deleting `vendor` and `node_modules` before running `make dev`?

2021-03-19 20:22 UTC, pierre-p-s commented
> have you tried deleting `vendor` and `node_modules` before running `make dev`?

Yes

2021-04-28 16:03 UTC, kongtiaowang approved these changes
LGTM

2021-04-28 16:12 UTC, pierre-p-s commented
We found a bug related to this. Fixing it now

2021-05-03 18:00 UTC, driusan commented
@pierre-p-s is this still needs work or can @kongtiaowang re-review it?

2021-05-03 18:22 UTC, pierre-p-s commented
@driusan Sorry forgot to delete the needs work tag. Yes it s ready for review

2021-05-08 17:01 UTC, kongtiaowang commented
After the 4th commit, the publication module can't save a publication into the database.

2021-06-08 16:00 UTC, driusan requested changes

2021-06-08 16:01 UTC, driusan commented on modules/publication/jsx/projectFields.js
> +    let published = this.props.formData.publishingStatus==='published';
These look like they should be const, not let

2021-06-10 13:48 UTC, pierre-p-s commented on modules/publication/ajax/FileUpload.php
> +        'WHERE Email = :e',
Reverted, will send a new PR

2021-06-10 14:39 UTC, pierre-p-s commented on modules/publication/ajax/FileUpload.php
> +        'WHERE Email = :e',
#7471

2021-06-15 17:07 UTC, driusan requested changes

2021-06-15 17:07 UTC, driusan commented on modules/publication/jsx/publicationIndex.js
> +      if (cell === 'inProgress') {
I don't think this is needed anymore?

2021-06-15 17:07 UTC, driusan commented on modules/publication/php/publication.class.inc
> +                'published'  => 'Published',
This seems to not match the db/react anymore either.

2021-06-18 15:57 UTC, pierre-p-s commented
Addressed comments and added a new field: Project.

2022-10-05 20:49 UTC, ridz1208 commented
@driusan this can be merged if you take a quick look at it

2022-10-14 16:45 UTC, merged