[Configuration] Adding mnc2bids converter configuration settings
aces/Loris pull request #7488
Opened 2021-06-18 14:35 UTC by AlexandraLivadas

Includes an SQL patch and changes to `SQL/0000-00-03-ConfigTables.sql` to add configuration settings to the Configuration module for the MINC to BIDS converter script
**To be discussed:** Descriptions and labels for each setting and the initial values for each setting

Below is a view of the new addition to the Configuration module:
<img width="1307" alt="Screen Shot 2021-06-18 at 10 22 22 AM" src="https://user-images.githubusercontent.com/35467361/122577511-df5ee080-d020-11eb-9772-8cc205a80b91.png">

#### Testing instructions 

1. Source the provided SQL patch
2. Check that the `MINC to BIDS Converter` settings appear in the Configuration module in your frontend
3. Check that submitting values for the related settings correctly updates the value in the frontend and backend

* Resolves #7477

2021-06-21 14:55 UTC, cmadjar reviewed
@AlexandraLivadas I had issues running the patch and had to do the following to make it run.

I will be modifying the back end LORIS-MRI script that uses this config today and will let you know how things go.

Thank you :)

2021-06-21 14:55 UTC, cmadjar commented on SQL/New_patches/2021-06-17_mnc2bids_Config_Settings.sql
> +INSERT INTO ConfigSettings (Name, Description, Visible, AllowMultiple, Label, OrderNumber) VALUE ('minc2bids', 'Settings related to converting MINC to BIDS', 1, 0,  'MINC to BIDS Converter', 13);
```suggestion
INSERT INTO ConfigSettings (Name, Description, Visible, AllowMultiple, Label, OrderNumber) VALUES ('minc2bids', 'Settings related to converting MINC to BIDS', 1, 0,  'MINC to BIDS Converter', 13);
```

2021-06-21 14:55 UTC, cmadjar commented on SQL/New_patches/2021-06-17_mnc2bids_Config_Settings.sql
> +--MINC to BIDS converter settings
```suggestion
-- MINC to BIDS converter settings
```

Not having the space make the patch impossible to source for some reason...

2021-06-21 14:55 UTC, cmadjar commented on SQL/0000-00-03-ConfigTables.sql
> +--MINC to BIDS converter settings
```suggestion
-- MINC to BIDS converter settings
```

2021-06-21 14:55 UTC, cmadjar commented on SQL/0000-00-03-ConfigTables.sql
> +--MINC to BIDS converter settings
since the missing space made the patch fail, I guess it would make this fail as well

2021-06-21 19:13 UTC, cmadjar requested changes
@AlexandraLivadas I modified the LORIS-MRI script to be reading the new Config settings and it works great! Now I am at the documentation part and noticed that the description of some of the fields could be improved a little bit. I noted only the Patch but the same should be applied in the default schema.

Thank you!!

2021-06-21 19:13 UTC, cmadjar commented on SQL/0000-00-03-ConfigTables.sql
> +INSERT INTO ConfigSettings (Name, Description, Visible, AllowMultiple, Label, OrderNumber) VALUES ('minc2bids', 'Settings related to converting MINC to BIDS', 1, 0,  'MINC to BIDS Converter', 13);
```suggestion
INSERT INTO ConfigSettings (Name, Description, Visible, AllowMultiple, Label, OrderNumber) VALUES ('minc2bids', 'Settings related to converting MINC to BIDS LORIS-MRI tool script', 1, 0,  'MINC to BIDS Converter', 13);
```

2021-06-21 19:13 UTC, cmadjar commented on SQL/0000-00-03-ConfigTables.sql
> +INSERT INTO ConfigSettings (Name, Description, Visible, AllowMultiple, DataType, Parent, Label, OrderNumber) SELECT 'bids_acknowledgments_text', 'Acknowledgments for the BIDS dataset', 1, 0, 'text',
```suggestion
INSERT INTO ConfigSettings (Name, Description, Visible, AllowMultiple, DataType, Parent, Label, OrderNumber) SELECT 'bids_acknowledgments_text', 'Acknowledgments to be added in the dataset_description.json file of the BIDS dataset created out of the MINC files', 1, 0, 'text', ID, 'BIDS Dataset Acknowledgments', 2 FROM ConfigSettings WHERE Name='minc2bids';
```

2021-06-21 19:13 UTC, cmadjar commented on SQL/0000-00-03-ConfigTables.sql
> +INSERT INTO ConfigSettings (Name, Description, Visible, AllowMultiple, DataType, Parent, Label, OrderNumber) SELECT 'bids_readme_text', 'README for the BIDS dataset', 1, 0, 'textarea', ID, 'BIDS Data
```suggestion
INSERT INTO ConfigSettings (Name, Description, Visible, AllowMultiple, DataType, Parent, Label, OrderNumber) SELECT 'bids_readme_text', 'Content to be added to the README of the BIDS dataset generated out of the MINC files', 1, 0, 'textarea', ID, 'BIDS Dataset README', 3 FROM ConfigSettings WHERE Name='minc2bids';
```

2021-06-21 19:13 UTC, cmadjar commented on SQL/0000-00-03-ConfigTables.sql
> +INSERT INTO ConfigSettings (Name, Description, Visible, AllowMultiple, DataType, Parent, Label, OrderNumber) SELECT 'bids_validator_options_to_ignore', 'Options to ignore for BIDS validation', 1, 1,
```suggestion
INSERT INTO ConfigSettings (Name, Description, Visible, AllowMultiple, DataType, Parent, Label, OrderNumber) SELECT 'bids_validator_options_to_ignore', 'Options to be ignored for BIDS validation', 1, 1, 'text', ID, 'BIDS Validation options to ignore', 4 FROM ConfigSettings WHERE Name='minc2bids';
```

2021-06-22 19:27 UTC, cmadjar approved these changes
Looks great! Thank you @AlexandraLivadas !

2021-06-22 19:27 UTC, cmadjar commented
@driusan ready for you :)

2021-07-12 13:37 UTC, merged

2021-07-12 13:39 UTC, driusan commented
Merging because this is how we've done things so far, but in the future I'm not sure it makes sense to send SQL patches to LORIS with just inserts for config settings that only affect the LORIS-MRI side. Why can't the LORIS-MRI scripts just validate/do the insert statements themselves if they're missing? There are no special permissions required and that would make it easier to maintain instead of needing to send/synchronize PRs to multiple repositories.