[CouchDB MRI Importer] Account for selected file(s)
aces/Loris pull request #7504
Opened 2021-07-06 16:29 UTC by jesscall

## Brief summary of changes
This PR helps resolve the issue reported in #6054, in which the argument checking for selected files was removed from the MRI importer script. This PR also adds support for the following cases: (a) multiple selected files, (b) no selected files.

The work here is taken from a previous PR (#5933), with some amendments.

#### Testing instructions (if applicable)

1. Run the script and check DQT to make sure that the correct files and QC info was imported.

#### Link(s) to related issue(s)

* Resolves #6054

2021-07-06 18:26 UTC, cmadjar requested changes
@jesscall this all looks good to me. I just noticed a few inconsistencies on how the result of the query would be labelled to resolve (sometimes camel case syntax is used, other times lower case). I went with the lower case suggestion but I don't have a strong preference on which convention to use as long as it looks the same ;).

I do not have a CouchDB set up to try the code. Maybe we could ask someone with CouchDB set up to test your PR on Thursday at the imaging meeting?

2021-07-06 18:26 UTC, cmadjar commented on tools/CouchDB_MRI_Importer.php
> +                    . '  ELSE "Multiple Selected files"'
```suggestion
                    . '  ELSE "Multiple selected files"'
```

2021-07-06 18:26 UTC, cmadjar commented on tools/CouchDB_MRI_Importer.php
> +                        'COALESCE(fqs.QCStatus, "No Qc on selected file")',
```suggestion
                        'COALESCE(fqs.QCStatus, "No QC on selected file")',
```

2021-07-06 18:26 UTC, cmadjar commented on tools/CouchDB_MRI_Importer.php
> +                    . '  ELSE "Unknown: multiple Selected files"'
```suggestion
                    . '  ELSE "Unknown: multiple selected files"'
```

2021-07-06 18:26 UTC, cmadjar commented on tools/CouchDB_MRI_Importer.php
> +             . 'LEFT JOIN files_qcstatus fqs USING (fileid) '
```suggestion
             . 'LEFT JOIN files_qcstatus fqs USING (FileID) '
```

2021-07-06 19:26 UTC, jesscall commented
@cmadjar Yes, sounds good. I could also ask someone from CCNA to test.

@pierre-p-s @CamilleBeau does one of you have time to test this ?

2021-07-08 14:11 UTC, pierre-p-s commented
Getting this error when running the script

![Screen Shot 2021-07-08 at 10 11 00 AM](https://user-images.githubusercontent.com/57676906/124936804-dab09b00-dfd4-11eb-987b-f02fc0238a9d.png)

2021-07-08 17:17 UTC, ridz1208 commented
@pierre-p-s the issue you are having seems unrelated to the PR. Are you sure you don't have an override that is not up to date and causing this error?

2021-07-19 18:48 UTC, pierre-p-s commented
> @pierre-p-s the issue you are having seems unrelated to the PR. Are you sure you don't have an override that is not up to date and causing this error?

I tried again with rb data and I m still getting the same error

2021-07-19 19:58 UTC, jesscall commented
@pierre-p-s sorry about that, should be good now

2021-07-28 18:57 UTC, pierre-p-s commented
I am getting this error

![Screen Shot 2021-07-28 at 2 56 23 PM](https://user-images.githubusercontent.com/57676906/127380271-4a68636d-3eb5-4c11-bb48-20629bfa55a8.png)

PHP:

![Screen Shot 2021-07-28 at 2 57 35 PM](https://user-images.githubusercontent.com/57676906/127380372-76d9356f-e635-4286-a90e-f116c0836d92.png)

2021-08-09 23:55 UTC, pierre-p-s commented
I tried to rerun and it works fine now... No idea what happened sorry about that

2021-08-10 14:16 UTC, pierre-p-s approved these changes

2021-09-07 21:18 UTC, cmadjar approved these changes
LGTM

2021-09-08 17:19 UTC, merged