[API] Sites endpoint
aces/Loris pull request #7771
Opened 2021-11-03 19:00 UTC by xlecours

API 0.0.4 dev
Returns the list of sites for an /api/v0.0.0.4-dev/sites GET request.

This is a rebased version of https://github.com/aces/Loris/pull/7466

2021-11-03 21:51 UTC, christinerogers requested changes
Hi Xavier, I've reviewed the alias/mri_alias part and can commit my suggested changes if you grant permission -- thanks. 
Any other parts of this PR I should look at in particular?

2021-11-03 21:51 UTC, christinerogers commented on modules/api/docs/LorisRESTAPI_v0.0.4-dev.md
> +`Alias` and `MRI alias` are short strings that are used as "tags" to identify a site or a group of sites. Those aliases are often used for display or file nameing purposes. (e.g: PSCID generation, mi
```suggestion
`Alias` and `MRI alias` are short strings that are used as "tags" to identify a site or a group of sites. Those aliases are often used for display or file naming purposes. (e.g: PSCID generation `MTL00001`). The `MRI alias` field is typically populated only for sites which collect imaging data. 
```

2021-11-03 21:51 UTC, christinerogers commented on modules/api/docs/LorisRESTAPI_v0.0.4-dev.md
> +* Note that only the `Name` property is unique accross all sites.
```suggestion
* Note that only the `Name` property is unique across all sites.
```
typo

2021-11-03 22:38 UTC, christinerogers approved these changes

2021-11-04 11:56 UTC, xlecours commented
@christinerogers Thanks for the corrections. Since you mentioned that some clients required this endpoint, can you tell if the current response structure and content is satisfying?

2021-11-09 00:29 UTC, christinerogers commented
> @christinerogers Thanks for the corrections. Since you mentioned that some clients required this endpoint, can you tell if the current response structure and content is satisfying?

Hi Xavier, given the `getSites` call returns the same information and response structure, nothing will break.  I took a look and I don't think anything changed regarding this particular response, true?  given I read that right, I give my 👍

2021-11-09 13:17 UTC, jesscall commented on modules/api/static/schema-v0.0.4-dev.yml
> +          description: A list of all sites; regardless of projects and/or user's permissions.
Should this be updated to reflect that there is a [userSiteMatch](https://github.com/aces/Loris/pull/7771/files#diff-53f7d851ca4412ecf8f287a9c194d02e267ef9e2705f7923a1f458308e565567R113) filter ?
```suggestion
          description: A list of all sites for the requesting user.
```

2022-10-31 15:40 UTC, maltheism requested changes
Conflict with Changelog

2023-03-14 15:04 UTC, laemtl commented
@xlecours I need that feature for the Wizard. Any chance that can be part of the next release? Let me know if I can help.

2023-03-28 14:31 UTC, merged