[user account] fix can't show email errors
aces/Loris pull request #7789
Opened 2021-11-05 15:55 UTC by kongtiaowang

## Brief summary of changes
fix the variable name
#### Testing instructions (if applicable)
input an invalid email to create or edit an user
#### Link(s) to related issue(s)
https://github.com/aces/Loris/issues/7746
* Resolves #  (Reference the issue this fixes, if any.
![Screen Shot 2021-11-05 at 11 44 09 AM](https://user-images.githubusercontent.com/9876007/140540146-f386da1a-7941-4f12-9565-f3976518ab1e.png)
)

2021-11-05 17:10 UTC, ridz1208 requested changes

2021-11-05 17:10 UTC, ridz1208 commented on modules/user_accounts/templates/form_edit_user.tpl
> +    {if $form.errors.Email_Group|default}
I don't think this is the correct solution, you are just undoing work from #7274 I think what should be done instead is to replace email_group in the edit_user class by "email" in the validate function.

2021-11-05 17:11 UTC, ridz1208 commented
@kongtiaowang have you checked that other fields in that same form haven't changed names as well ?

Read the issue (#7746) carefully there are more details there

2021-11-08 13:59 UTC, kongtiaowang commented
@ridz, could you review again?

2021-11-08 16:30 UTC, ridz1208 approved these changes
Code looks good

2021-11-08 16:30 UTC, ridz1208 commented
@racostas could you test please ?

2021-11-09 14:14 UTC, racostas commented
LGTM

... a related issue:

When a user request an account by itself (not created by the admin) the validations in the email field are not triggered. We should do this consistent.

![image](https://user-images.githubusercontent.com/37309344/140939596-57bef71b-cdb9-46cd-8661-999f7c338bd1.png)

![image](https://user-images.githubusercontent.com/37309344/140939780-0f71a1eb-cca2-416b-9810-5f9570a465c0.png)

2021-11-10 14:48 UTC, ridz1208 commented
@racostas please make a separate issue for what you have found

2021-11-11 21:02 UTC, merged