[user_accounts] User with only superuser permission selected can edit other user's permissions
aces/Loris pull request #7808
Opened 2021-11-08 22:26 UTC by AlexandraLivadas

## Brief summary of changes
**This change is up for discussion**
If a user has superuser permission but no other permissions individually selected, they were not able to edit the permissions of another user. This was because the method `getPermissionIDs` did not include an override for superusers that would return the entire list of permissions. This override is added so that a superuser can edit all permissions of another user. These changes match the logic of the similar function `getPermissionsVerbose`.

#### Testing instructions (if applicable)

1. Create a new user and select the superuser permission but not any other permissions specifically
2. Logged in as that superuser, go to some other user that has some permissions already set.
3. Add/delete permissions for that user.
4. See that the permission list is correctly updated once the page is reloaded and in the backend.

#### Link(s) to related issue(s)

* Resolves #7657

2021-11-09 15:46 UTC, driusan commented
Linked issue is tagged as critical, PR should probably be too..

2021-11-10 14:53 UTC, ridz1208 commented
@AlexandraLivadas tests are failing

And can you detail what's the required discussion ?

2021-11-23 16:42 UTC, maltheism approved these changes

2021-11-23 16:56 UTC, driusan commented
@AlexandraLivadas just noticed this is still failing

2021-12-03 19:59 UTC, ridz1208 commented
@AlexandraLivadas given the few places where that function is used in the edit_user logic and the complexity of the edit_user form I think the best path is not to amend the getPermissionIDs directly (because we might still want to know the real permissions assigned to a "superuser" especially when a user is made superuser exceptionally or erroneously. With this PR is a superuser edits another superuser they will automatically associate them with ALL permissions without wanting to do it).


Instead I think you should just alter the logic of the setup function to allow for the permissions to be displayed even if not checked when the user is a superuser.

2021-12-10 18:21 UTC, ridz1208 commented on modules/user_accounts/php/edit_user.class.inc
>              // granted.
```suggestion
            // granted. Unless they are a superuser
```

2021-12-10 21:15 UTC, ridz1208 commented
@AlexandraLivadas I think the description at the top here needs updating given the latest changes

2021-12-10 21:45 UTC, ridz1208 requested changes
It seems to be working for adding a permission but not for removing a permission

ie. login as a superuser with no other permissions than the superuser one -> add a couple permissions to another user -> save and reload ->permissions are selected -> try to remove one of those permissions -> reload after save -> permission is still there

2022-01-11 19:19 UTC, AlexandraLivadas commented
@ridz1208 Ready for re-review

2022-09-28 23:04 UTC, ridz1208 approved these changes

2022-09-29 14:05 UTC, merged