[NDB_BVL_Instrument] fix support for JSONData instruemnts
aces/Loris pull request #7818
Opened 2021-11-10 20:08 UTC by ridz1208

## Brief summary of changes
Fix a couple instances where the Instrument class does nnot support JSONData instruments by either looking for a specific field in the not-yet-populated instrument data object or using the `$this->table` variable

2021-11-10 21:36 UTC, ridz1208 commented
@driusan @kongtiaowang I'm not sure why this is still failing. On my VM everything seems functional

2021-11-10 22:23 UTC, ridz1208 commented
@kongtiaowang on line 129 of `NDB_BVL_Instrument_Test.php` the get datadisctionary returns an empty array. It needs to be changed to return DictionaryItems I'm just not sure how to make mock items

2021-11-10 23:30 UTC, ridz1208 commented
@kongtiaowang @driusan after 17000 tries, I think I got it right

2021-11-11 18:01 UTC, ridz1208 commented
@zaliqarosli would you be able to test this one ?

2021-11-16 15:27 UTC, ridz1208 commented
blocking https://github.com/aces/Loris/pull/7809

2021-11-16 21:35 UTC, zaliqarosli commented
i'm getting a different error on both this PR branch and main. is there a patch im missing?

```
[Tue Nov 16 16:31:49.714552 2021] [php7:notice] [pid 27212] [client 10.127.130.109:52076] [DEBUG] Module handle function called, referer: http://zrosli-dev.loris.ca/instruments/bmi/?candID=300001&sessionID=1&commentID=300001MTL0011221465332127
[Tue Nov 16 16:31:49.765644 2021] [php7:notice] [pid 27212] [client 10.127.130.109:52076] [DEBUG] Page bmi not found, referer: http://zrosli-dev.loris.ca/instruments/bmi/?candID=300001&sessionID=1&commentID=300001MTL0011221465332127
[Tue Nov 16 16:31:49.765726 2021] [php7:notice] [pid 27212] [client 10.127.130.109:52076] [DEBUG] Loading bmi , referer: http://zrosli-dev.loris.ca/instruments/bmi/?candID=300001&sessionID=1&commentID=300001MTL0011221465332127
[Tue Nov 16 16:31:49.814912 2021] [php7:notice] [pid 27212] [client 10.127.130.109:52076] [DEBUG] NDB_Page middleware called, referer: http://zrosli-dev.loris.ca/instruments/bmi/?candID=300001&sessionID=1&commentID=300001MTL0011221465332127
```

![Screen Shot 2021-11-16 at 4 34 13 PM](https://user-images.githubusercontent.com/17415878/142069539-e3ba04fc-e53a-452e-8f00-40fa89a5a541.png)

2021-11-16 21:37 UTC, ridz1208 commented
@zaliqarosli is the BMI instruemnt set up on your VM ? (if not you need to copy it from raisinbread/instruments into project instruments)

2021-11-16 21:45 UTC, zaliqarosli commented
@ridz1208 yeah the instrument loads fine for me

![Screen Shot 2021-11-16 at 4 40 21 PM](https://user-images.githubusercontent.com/17415878/142070792-a586364c-f3a3-4fd0-811b-f67cb16ad1e1.png)

I just get the 500 error with no useful messages in my apache log when I try to 'Save' data

2021-11-16 22:04 UTC, zaliqarosli commented
@ridz1208 yes

2021-11-16 22:05 UTC, ridz1208 commented
@zaliqarosli if only we could know what the error is lol

2021-11-16 22:30 UTC, zaliqarosli commented
i get 500 again and only a bunch of select statements in my log

```
[Tue Nov 16 17:28:17.716416 2021] [php7:notice] [pid 28082] [client 10.127.138.104:55978] [DEBUG] SELECT cs.ID as ParentID, child.ID as ChildID,\n                        cs.AllowMultiple, child.Name\n                FROM ConfigSettings cs\n                    LEFT JOIN ConfigSettings child ON (child.Parent=cs.ID)\n                WHERE cs.ID=:101, referer: http://zrosli-dev.loris.ca/instruments/bmi/?commentID=300001MTL0011221465332127&sessionID=1&candID=300001
[Tue Nov 16 17:28:17.717588 2021] [php7:notice] [pid 28082] [client 10.127.138.104:55978] [DEBUG] SELECT Value FROM Config WHERE ConfigID=:101 LIMIT 2, referer: http://zrosli-dev.loris.ca/instruments/bmi/?commentID=300001MTL0011221465332127&sessionID=1&candID=300001
[Tue Nov 16 17:28:17.719192 2021] [php7:notice] [pid 28082] [client 10.127.138.104:55978] [DEBUG] SELECT cs.ID as ParentID, child.ID as ChildID,\n                        cs.AllowMultiple, child.Name\n                FROM ConfigSettings cs\n                    LEFT JOIN ConfigSettings child ON (child.Parent=cs.ID)\n                WHERE cs.ID=:102, referer: http://zrosli-dev.loris.ca/instruments/bmi/?commentID=300001MTL0011221465332127&sessionID=1&candID=300001
[Tue Nov 16 17:28:17.720336 2021] [php7:notice] [pid 28082] [client 10.127.138.104:55978] [DEBUG] SELECT Value FROM Config WHERE ConfigID=:102 LIMIT 2, referer: http://zrosli-dev.loris.ca/instruments/bmi/?commentID=300001MTL0011221465332127&sessionID=1&candID=300001
[Tue Nov 16 17:28:17.722055 2021] [php7:notice] [pid 28082] [client 10.127.138.104:55978] [DEBUG] SELECT cs.ID as ParentID, child.ID as ChildID,\n                        cs.AllowMultiple, child.Name\n                FROM ConfigSettings cs\n                    LEFT JOIN ConfigSettings child ON (child.Parent=cs.ID)\n                WHERE cs.ID=:103, referer: http://zrosli-dev.loris.ca/instruments/bmi/?commentID=300001MTL0011221465332127&sessionID=1&candID=300001
[Tue Nov 16 17:28:17.723227 2021] [php7:notice] [pid 28082] [client 10.127.138.104:55978] [DEBUG] SELECT Value FROM Config WHERE ConfigID=:103 LIMIT 2, referer: http://zrosli-dev.loris.ca/instruments/bmi/?commentID=300001MTL0011221465332127&sessionID=1&candID=300001
[Tue Nov 16 17:28:17.724786 2021] [php7:notice] [pid 28082] [client 10.127.138.104:55978] [DEBUG] SELECT cs.ID as ParentID, child.ID as ChildID,\n                        cs.AllowMultiple, child.Name\n                FROM ConfigSettings cs\n                    LEFT JOIN ConfigSettings child ON (child.Parent=cs.ID)\n                WHERE cs.ID=:106, referer: http://zrosli-dev.loris.ca/instruments/bmi/?commentID=300001MTL0011221465332127&sessionID=1&candID=300001
[Tue Nov 16 17:28:17.725929 2021] [php7:notice] [pid 28082] [client 10.127.138.104:55978] [DEBUG] SELECT Value FROM Config WHERE ConfigID=:106 LIMIT 2, referer: http://zrosli-dev.loris.ca/instruments/bmi/?commentID=300001MTL0011221465332127&sessionID=1&candID=300001
```

2021-11-16 22:31 UTC, ridz1208 commented
@driusan i dont know what happened to exceptions but as you can see... impossible to debug

2021-11-16 23:12 UTC, ridz1208 commented
@zaliqarosli please test/review again. if possible with both a linst and non linst instrument

2021-11-16 23:13 UTC, ridz1208 commented on php/libraries/NDB_BVL_Instrument_LINST.class.inc
> +                    $this->testName.'_Date_taken',
@driusan all changes made to this file it to make it at par with the `LorisFormDictionaryImpl.class.inc` which prefixes all dictionary items with the instrument name

2021-11-22 18:25 UTC, zaliqarosli requested changes
works exactly as should with a linst file.

with a non-linst file, the data saves fine and scores are correctly updated and saved.
BUT for some reason, on clicking 'Save Data' on the Top page, the page refreshes and takes you to the 'General Observations' (3rd) page, with a weird combination of both the top page and general observations page rendered. (this does not happen on main branch)

<img width="1173" alt="Screen Shot 2021-11-22 at 1 19 20 PM" src="https://user-images.githubusercontent.com/17415878/142915269-1057deea-e175-41d4-8274-a2d5a64ef256.png">

2021-11-22 22:23 UTC, ridz1208 commented on php/libraries/NDB_BVL_Instrument.class.inc
> +        )->getDataDictionary();
@driusan `getDataDictionary()` modifies the `$this->page` value altering the active page of the instrument causing the weird page change on save.

I fixed it here simply by getting the data dictionary from another instance of the same instrument... I don't like the fact that getDataDictionary modifies the instrument on which it is called however. To be discussed

2021-11-22 23:45 UTC, zaliqarosli approved these changes
works well now

2021-11-24 00:00 UTC, ridz1208 commented
@zaliqarosli this PR has changed a little, could you please re-test only PHP instruments?

2021-11-24 17:02 UTC, zaliqarosli approved these changes
still works!

2021-11-24 17:03 UTC, ridz1208 commented
@driusan PLEASE MERGE BEFORE IT BREAKS AGAIN

2021-11-24 17:36 UTC, merged