[instrument_builder] ADDED: field warnings for maximum length in Instrument Builder module
aces/Loris pull request #8112
Opened 2022-06-11 16:55 UTC by satvik-tha-god

…t Builder

## Brief summary of changes
* Added field warnings for length for `_status` fields: 
* Added field warnings for length for all the fields
* Minor spelling mistake fix

#### Testing instructions (if applicable)
1. Go to /instrument_builder/#Build 
2. Check for warnings for input length greater than 57 for the following fields by clicking Add Row 
    1. Data entry->Textbox->Question Name
    2. Data entry->Textarea->Question Name
    3. Data entry->Date->Question Name
    4. Data entry->Numeric->Question Name
3. Check for warnings for input length greater than 64 for the rest of the Question Name and Question Text fields by clicking Add Row

#### Link(s) to related issue(s) 

* Resolves #7582

2022-06-13 15:00 UTC, christinerogers commented
Great stuff, Satvik!  It would be great to have an idea of how the warnings will appear to the end user - could you kindly post a screenshot in this thread, showing the error message in context?  Thanks, that would be really helpful in speeding this through the review process.

2022-06-13 20:22 UTC, satvik-tha-god commented
> Great stuff, Satvik! It would be great to have an idea of how the warnings will appear to the end user - could you kindly post a screenshot in this thread, showing the error message in context? Thanks, that would be really helpful in speeding this through the review process.

@christinerogers  Thanks!  Here are the screenshots
![Screenshot from 2022-06-14 01-50-55](https://user-images.githubusercontent.com/64309880/173438408-ae22af38-4525-4e3f-bd73-277d1492e9be.png)
![Screenshot from 2022-06-14 01-50-39](https://user-images.githubusercontent.com/64309880/173438450-ff1311e9-e103-4f05-9435-9e2bc3758629.png)

2022-06-13 22:29 UTC, christinerogers requested changes
Hi @satvik-tha-god thanks for this PR! 
I've suggested edits for the error messages to let the user know directly what they should do (shorten it). Thanks Satvik for checking over the numbers I included. 
@racostas - over to you to check if this satisfies the issue / all cases etc.

2022-06-13 22:29 UTC, christinerogers commented on modules/instrument_builder/jsx/react.questions.js
> +      temp.questionName = 'Field length should be strictly less than 65 characters';
```suggestion
      temp.questionName = 'Please shorten to 64 characters maximum';
```

2022-06-13 22:29 UTC, christinerogers commented on modules/instrument_builder/jsx/react.questions.js
> +      temp.questionName = 'Field length should be strictly less than 58 characters';
```suggestion
      temp.questionName = 'Please shorten to 57 characters maximum';
```
@satvik-tha-god - please check these carefully as I translated your `less than 58` to `57 maximum` - is this accurate?

2022-06-14 02:51 UTC, racostas commented
Hi @satvik-tha-god,
Great work !!
Please address @christinerogers comments.
The unit test are falling due to code standard nonconformity. You will be able to identify the error entering in the failed test and searching for the _**error**_ keyword in the output. For this case are simple ones. I attach a screenshot for reference.

![image](https://user-images.githubusercontent.com/37309344/173483110-a23ffedb-e98a-4723-9862-a3e4675a85d5.png)

2022-07-28 14:09 UTC, racostas commented
Not sure why but it seems some of the test got cancelled. 

![image](https://user-images.githubusercontent.com/37309344/181525858-3cd5b647-6d1e-403d-9c4e-4098df228b49.png)

Please relaunch the jobs.

2022-08-31 16:01 UTC, racostas commented
failing a the test suit, nevertheless I don't see direct relation avec this PR itself. What do you think @driusan ?

2022-10-24 13:35 UTC, racostas requested changes
Thank you @satvik-tha-god for those fixes. 
I think the only thing missing is to update the `modules/instrument_builder/test/TestPlan.md` accordingly. Could you please take a look into it when you get a chance ?
I'm cc @christinerogers as she might want to take a look as well since she identified the original issue.

2022-12-07 14:28 UTC, merged

2022-12-07 14:28 UTC, driusan commented
I think we can merge this and then send another PR to fix the test plan.