[Dashboard][Recruitment] Added candidate age ranges pie chart to recruitment dashboard
aces/Loris pull request #8134
Opened 2022-07-11 14:15 UTC by satvik-tha-god

## Brief summary of changes

* Added the candidate age ranges Pie chart for the following ranges:  less than 60, 60-64, 65-69, 70 - 74, 75-79, 80-85, 86 or more to recruitment
* Updated the layout of the other components to fit better
* Added the necessary AJAX and utility JS functions
* Added PHP backend code for related

## Screenshots:
![Screenshot from 2022-07-11 19-42-36](https://user-images.githubusercontent.com/64309880/178284556-17a35ff3-56f0-43ee-8c76-8398c8d31256.png)
![Screenshot from 2022-07-11 19-44-14](https://user-images.githubusercontent.com/64309880/178284848-0a5e9ba3-f847-44d4-a53e-752ae26683bc.png)

#### Link(s) to related issue(s)

* Resolves #8133   (Reference the issue this fixes, if any.)

2022-07-27 13:30 UTC, racostas reviewed
Hi Satvik, nice work !! For making this graph more generalizable let's please take the minimum and maximum age from the project configuration.

Also let's try to show in the graph not just the percentage of candidates in the range but also the "total count". This maybe will have to be done in a new PR.

2022-08-31 16:47 UTC, christinerogers commented
@racostas is this ready for @driusan to review?

2022-09-27 16:45 UTC, christinerogers commented
@racostas probably best if you re-review

2022-10-04 14:57 UTC, racostas approved these changes
LGTM.

2022-10-04 15:05 UTC, driusan commented on modules/statistics/php/charts.class.inc
> +                           WHERE c.DoB IS NOT NULL
this is missing `c.Active='Y'`

2022-10-04 15:11 UTC, racostas commented
> see last two comments about console.error and fixing the query

^ @satvik-tha-god

2022-10-24 13:39 UTC, racostas requested changes
Hi @satvik-tha-god , it seems the test suit is failing after the latest changes. Could you please take a look when you get a chance ? 
Many thanks.

2022-12-07 15:37 UTC, racostas commented
A wider/extensible solution is currently given to this issue at CCNA project. The plan is to merge all this changes from CCNA to LORIS core soon. For this reason I think this PRs got outdated. It worth to mention nevertheless that the principles and solutions prosed here were the base for the solution currently been implemented at CCNA (the one that will be merged back to LORIS core). 

For this reason I'm closing this PR.

2022-12-07 15:37 UTC, closed without merging