[core][api] fix invalid date error
aces/Loris pull request #8176
Opened 2022-09-30 16:35 UTC by regisoc

## Context

Several behaviours related to date parsing. In some cases, when using `/new_profile` or `/api/v0.0.3/candidates` to add candidates, date parsing allowed date such as 0000-00-00 or with possible multiple separators when only months were provided (e.g. 'yyyy/mm'). 

## Brief summary of changes

This fix:

- checks and normalizes multiple date formats. E.g. valid date formats: 'yyyy-mm', 'dd/mm/yyyy', 'yyyy-mm-dd'.
- returns 400 Bad Requests/JSON errors for invalid dates.

#### Testing instructions (if applicable)

1. Log into to get a `token`: 
```bash
curl -v -k -X 'POST' \
  'https://<hostname>/api/v0.0.3/login' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "username": "<username>",
  "password": "<password>"
}'
```
2. Test for `/api/v0.0.3/candidates` endpoint:
```bash
curl -v -k -X POST 'https://<hostname>/api/v0.0.3/candidates' \
    -H "Authorization: Bearer <token>" \
    -d '{
        "Candidate": {
            "Project": "Rye",
            "Site": "Montreal",
            "DoB": "<a_date>",
            "Sex": "Female"
        }
    }'
```
3. Test for `/new_profile` endpoint:
```bash
curl -v -k -X POST \
  'https://<hostname>/new_profile' \
  -H "Authorization: Bearer <token>" \
  -F site='1' \
  -F project='3' \
  -F dobDate='<a_date>' \
  -F sex='female'
```

#### Link(s) to related issue(s)

* Resolves #8127
* Resolves #8144

2022-10-04 15:59 UTC, xlecours requested changes
I don't understand the purpose of these changes. Is it to allow invalide dates to bypass the interface specifications? If we say that the backend expect a YYYY-MM-DD date then the clients needs to provide a YYYY-MM-DD date. 
As for the date range (YYYY-MM), in the end, it will need to be put in a SQL date data type column. the parseDate function only adds `-01` to the value; something that the clients should be able to do.  (And I believe our javascript client is doing that by truncating the returned value of the date picker.)

2022-10-04 15:59 UTC, xlecours commented on php/libraries/Candidate.class.inc
> +        if ($dob < new \DateTime('1900-01-01')) {
This is arbitrary. Why is there a limit ?

2022-10-04 15:59 UTC, xlecours commented on php/libraries/Candidate.class.inc
> +declare(strict_types=1);
Why is this changed?

2022-10-04 15:59 UTC, xlecours commented on modules/new_profile/php/new_profile.class.inc
> +                $errors['dobDate'] = 'Date of Birth cannot be set before 1900.';
Why?

2022-10-04 15:59 UTC, xlecours commented on modules/api/php/endpoints/candidates.class.inc
> +declare(strict_types=1);
Why is this changed? Is it a new convention?

2022-10-04 15:59 UTC, xlecours commented
@regisoc This is unrelated to the API. The title should be changed.

2022-10-04 16:04 UTC, xlecours commented
@regisoc Should EDC be handled the same way?

2022-11-09 20:07 UTC, closed without merging

2022-11-09 20:24 UTC, ridz1208 commented
@regisoc @xlecours  this was automatically closed because the branch was issued from aces

make sure to only issue PRs from you fork of LORIS

you can still move the contents of this branch to your fork and re-issue the PR if necessary (you should still have the branch locally)

2022-12-13 15:45 UTC, regisoc commented
Yes will do it today