Instruments qe
aces/Loris pull request #8216
Opened 2022-11-04 18:57 UTC by driusan

This adds a QueryEngine for the instruments module. The Instrument
QueryEngine bulk loads the data so that it can work with either JSON
or SQL instruments, and then compares the data that was loaded
against the criteria given.

This is intended to be an example of a QueryEngine for PR#8215.

It could use more automated tests but tests for instruments are difficult
since they're so highly customized per project.

2022-12-07 17:56 UTC, driusan commented
Blocked by #8260, which adds the getQueryEngine function and removes getDataDictionary from the module descriptor class.

2023-04-04 19:02 UTC, xlecours requested changes
partial review

2023-04-04 19:12 UTC, driusan commented on modules/instruments/php/instrumentqueryengine.class.inc
> +    private $visitcache = [];
done

2023-04-05 11:28 UTC, xlecours reviewed
I havn't manage to make it populated the dictionary module. Should it?

2023-04-05 11:39 UTC, xlecours commented
More on a design perspective, I have doubts regarding the Instantiation of an instrument for each row in the flag table and keeping them in memory then applying the filtering using Criteria\*. 
Could the bulkLoadInstrument yield lightweight objects that could be pass to Criteria and Instantiate Instruments after that if necessary? Something like FilterIterator with an accept function.

2023-04-05 12:08 UTC, driusan commented
1. Yes, the dictionary module should be populated. Any instruments you have in your test_names table should be there.
2. In my testing, the bulkLoadInstanceData wasn't heavy. The overhead comes from repeated calls to \NDB_Factory (and all the SQL calls it makes) which bulkLoad avoids, not the memory requirements of holding the instrument's data in memory. We can revisit later if it proves to be a problem, but I was able to handle fairly large instruments without memory problems when I wrote/tested this. We need to handle both JSON data and SQL table-based instruments, so we always need the instantiated instruments and the overhead of having to call NDB_Factory shadows the overhead of doing it once and keeping the data in memory.

2023-04-26 16:18 UTC, merged