[EEG Browser] Multiple coord systems
aces/Loris pull request #8242
Opened 2022-11-25 14:42 UTC by regisoc

Save any coordinate system file (CapTrak, CTF, ...) into the db.

2022-12-12 19:38 UTC, laemtl commented on SQL/New_patches/2022-11-24-electrode-coord-system.sql
> +CREATE TABLE IF NOT EXISTS `physiological_coord_system` (
I think the landmarks are not always NAS/LPA/RPA, and we can also have HeadCoil/DigitizedHeadPoints as well. Maybe a more generalized approach would be to store head points in a separate table physiological_head_point:

`HeadPointID`               INT(10)     UNSIGNED  NOT NULL AUTO_INCREMENT,
`PhysiologicalCoordSystemID` INT(10)     UNSIGNED  NOT NULL,
`Name`                          VARCHAR(50)     NOT NULL,
`X`                                 DECIMAL(12,6)    NOT NULL,
`Y`                                 DECIMAL(12,6)    NOT NULL,
`Z`                                 DECIMAL(12,6)    NOT NULL

With FOREIGN KEY (`PhysiologicalCoordSystemID`)
REFERENCES `physiological_coord_system` (`PhysiologicalCoordSystemID`)

or anything equivalent.

2022-12-12 19:39 UTC, laemtl commented
The rest LGTM

2023-01-16 13:46 UTC, regisoc commented
- [ ] insert into schema
- [ ] insert into RB

2023-01-23 21:55 UTC, regisoc commented
Rebased to #8336 (main -> 24.1)

2023-02-10 16:22 UTC, christinerogers commented
per Loris-EEG meeting (from a question by @oldgandalf)

Are the global standards: 10-10, 10-5, 305 coordinate standards covered by this PR? 
@laemtl @regisoc cc @cmadjar 
(If so, please update the PR description at top so we can let the world know)

2023-02-12 21:00 UTC, regisoc commented
This PR does not cover these standard, it covers the way of saving multi-coordinate systems and electrodes encountered during parsing. This means it register all coordinate system types (e.g. fiducials, anatomical landmarks), names (e.g. CapTrak, CTF), units and modalities found inside a BIDS file, and their associated electrode information. 

For what I can see, the BIDS format put standards like `10-20` and `10-10` into the `EEGPlacementScheme` attribute, which is [a recommended but not mandatory section for `_eeg.json` files](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/03-electroencephalography.html#sidecar-json-_eegjson).

I have looked into several BIDS archives we have, and only find this attribute to be not used , i.e. `"EEGPlacementScheme": "n/a"`. Maybe we can add this into another issue to include it? 
Even so, it must be present in the BIDS `_eeg.json` files to be saved.

2023-02-24 06:56 UTC, laemtl approved these changes

2023-02-28 17:15 UTC, jeffersoncasimir requested changes

2023-02-28 17:15 UTC, jeffersoncasimir commented on SQL/New_patches/2022-11-24-electrode-coord-system.sql
> +  DROP COLUMN PhysiologicalFileID;
This line breaks functionality [here](https://github.com/aces/Loris/blob/main/modules/electrophysiology_browser/php/sessions.class.inc#L607)

2023-03-03 15:44 UTC, jeffersoncasimir approved these changes
Works as expected. Great work!

2023-03-06 16:26 UTC, merged