[core] return error message on invalid dob
aces/Loris pull request #8267
Opened 2022-12-13 21:07 UTC by regisoc

## Brief summary of changes

When using `/api/v0.0.3/candidates` with an invalid date format, returns 400 Bad Requests/JSON errors.
This PR checks the date of birth and returns the correct format in the message ('yyyy-mm-dd').

#### Testing instructions (if applicable)

1. Log into to get a token:

```bash
curl -v -k -X 'POST' \
  'https://<hostname>/api/v0.0.3/login' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "username": "<username>",
  "password": "<password>"
}'
```

2. Test for `/api/v0.0.3/candidates` endpoint:

```bash
curl -v -k -X POST 'https://<hostname>/api/v0.0.3/candidates' \
    -H "Authorization: Bearer <token>" \
    -d '{
        "Candidate": {
            "Project": "Rye",
            "Site": "Montreal",
            "DoB": "<a_date>",
            "Sex": "Female"
        }
    }'
```

#### Link(s) to related issue(s)

* #8127

2022-12-14 15:22 UTC, xlecours requested changes

2022-12-14 15:22 UTC, xlecours commented on php/libraries/Candidate.class.inc
> +        }
```suggestion
        if (!empty(\DateTime::getLastErrors())) {
            error_log(print_r(\DateTime::getLastErrors(), true));
            throw new InvalidArgumentException(
                "Date of Birth is invalid (expected format: YYYY-MM-DD)",
                DOB_INVALID
            );
        } 
```

2022-12-14 15:22 UTC, xlecours commented on php/libraries/Candidate.class.inc
> +        if (is_bool($dob) && $dob === false) {
is_bool is always true when `$dob === false`

2022-12-15 15:07 UTC, xlecours requested changes

2022-12-15 15:07 UTC, xlecours commented on php/libraries/Candidate.class.inc
> +            error_log(print_r($dob->getLastErrors(), true));
I think that getLastError is static. It should be called using `\DateTime::getLastErrors()`

2022-12-15 15:11 UTC, xlecours commented on php/libraries/Candidate.class.inc
> +            error_log(print_r($dob->getLastErrors(), true));
Looking at documentation
https://www.php.net/manual/en/datetime.getlasterrors.php
It returns an array or false so `!empty` is always true.

2022-12-15 15:16 UTC, xlecours commented on php/libraries/Candidate.class.inc
> +            error_log(print_r($dob->getLastErrors(), true));
I tried it and when there are no errors, it returns the following:
```
array(4) {
  ["warning_count"]=>
  int(0)
  ["warnings"]=>
  array(0) {
  }
  ["error_count"]=>
  int(0)
  ["errors"]=>
  array(0) {
  }
}
```
That is not empty.
 You were right in checking for `error_count === 0 and warning_count === 0`

2022-12-15 15:36 UTC, xlecours requested changes

2022-12-15 15:36 UTC, xlecours commented on php/libraries/Candidate.class.inc
> +        $dob = DateTime::createFromFormat('Y-m-d', $dateOfBirth);
please add `!` in front of the format so that the resulting date has 00:00:00 as its time portion rather than the current time.

2022-12-15 17:43 UTC, xlecours approved these changes

2022-12-15 17:49 UTC, regisoc commented
@xlecours do I need a rebase to 24.1 for this PR?

2022-12-15 19:08 UTC, xlecours commented
> @xlecours do I need a rebase to 24.1 for this PR? I am not entirely sure

I am not sure actually. I would say, send a PR to 24.1 as well.
@driusan ?

2022-12-15 20:39 UTC, driusan commented on php/libraries/Candidate.class.inc
> +            error_log(print_r(\DateTime::getLastErrors(), true));
Leftover debug statement?

2022-12-15 20:39 UTC, driusan commented
Yes, 24.1 is the latest release, so it still gets bug fixes.

2022-12-16 04:03 UTC, regisoc commented
Duplicated to #8279

2022-12-16 19:15 UTC, driusan commented
don't duplicate PRs, they'll get pulled forward eventually.. just rebase this one

2022-12-18 20:38 UTC, regisoc commented
There are lots of changes for the rebase.
If that is ok, I will close this PR and keep the other one, the branch is already up-to-date with 24.1 on the other one.

2022-12-18 20:40 UTC, closed without merging