[Issue tracker] - fix can't Delete attachment #8006
aces/Loris pull request #8337
Opened 2023-01-24 14:05 UTC by kongtiaowang

[Issue tracker] - Delete attachment #8006

- [ ] Have you updated related documentation?
 [Issue tracker] - fix can't Delete attachment #8006
A clear and concise description of what the bug is
If a user does not have Issue Tracker: Close/Edit/Re-assign/Comment on All Issues, they cannot delete their own attachment.
#### Testing instructions (if applicable)
If a user does not have Issue Tracker: Close/Edit/Re-assign/Comment on All Issues, they can delete their own attachment.

2023-02-14 15:14 UTC, ridz1208 commented
@kongtiaowang can you rebase this to go to 24.1-release please

2023-03-06 15:13 UTC, ridz1208 commented
@GeorgeMurad could you please test this so we merge it into the next bugfix ?

2023-03-06 15:19 UTC, GeorgeMurad commented
@ridz1208 I will!.

2023-03-22 19:49 UTC, zaliqarosli requested changes
this.state.issueData doesn't exist

2023-03-22 19:49 UTC, zaliqarosli commented on modules/issue_tracker/jsx/attachments/attachmentsList.js
> +      || this.state.issueData.whoami === item.user) {
issueData isn't a defined state in this class. not sure what this is supposed to be?

2023-03-22 21:35 UTC, zaliqarosli commented
@GeorgeMurad any chance you could re-test this? thanks!

2023-03-28 16:03 UTC, zaliqarosli commented
@kongtiaowang i feel like i should review this cz i made changes 😅 @driusan anyone who should/can review this? @laemtl ? it's quite quick

2023-03-28 16:19 UTC, laemtl commented
@zaliqarosli  If this passes @GeorgeMurad tests maybe he can approves it?

2023-03-28 16:23 UTC, GeorgeMurad commented
@laemtl Yes, I tested  it and it passes.

2023-03-28 16:46 UTC, merged