[Tools] CouchDB_Import_MRI.php cleanup
aces/Loris pull request #8340
Opened 2023-01-25 17:09 UTC by laemtl

- Remove the side effect in CouchDB_MRI_Importer.php
- Migrate CouchDB_MRI_Importer.php in importers/
- Migrate the import statements in CouchDB_MRI_Importer.php

2023-03-03 16:22 UTC, laemtl commented
@cmadjar Your pb should be fixed with #8369.

2023-03-03 16:34 UTC, cmadjar approved these changes
LGTM

2023-03-06 15:36 UTC, driusan requested changes

2023-03-06 15:36 UTC, driusan commented on tools/importers/CouchDB_MRI_Importer.php
> +require_once __DIR__ . '/../../vendor/autoload.php';
This is included by generic_includes

2023-03-06 15:36 UTC, driusan commented on tools/importers/CouchDB_MRI_Importer.php
> +require_once __DIR__ . '/../generic_includes.php';
requiring is a side-effect, it should be in the other file not the class definition file.

2023-03-06 15:36 UTC, driusan commented on tools/importers/CouchDB_MRI_Importer.php
> +require_once 'FeedbackMRI.class.inc';
These are all autoloaded

2023-03-06 16:39 UTC, laemtl commented
@driusan Done

2023-03-06 16:58 UTC, merged