[Acknowledgements] data framework
aces/Loris pull request #8365
Opened 2023-02-10 18:35 UTC by kongtiaowang

## Brief summary of changes

rewrite [Acknowledgements] data framework
#### Testing instructions (if applicable)

2023-02-22 00:02 UTC, miladheshmati commented
@laemtl, could you please let me know that should I code review or test this?

2023-03-27 14:11 UTC, ridz1208 commented
@miladheshmati given that its a full module change a wise thing would be to follow the module test plan

2023-09-26 13:45 UTC, xlecours commented
@miladheshmati Can you take a look at this one again?

2023-10-10 18:25 UTC, miladheshmati commented
@kongtiaowang @xlecours I'm getting this error on the front-end as I switch to this branch and do a make dev:

![Screenshot 2023-10-10 at 2 21 32 PM](https://github.com/aces/Loris/assets/51356424/82dbb89a-73b2-4ff9-a667-f97fe5f30477)

2025-02-21 18:07 UTC, christinerogers commented
@kongtiaowang should this be merged for the 27 release? If so can you suggest a new reviewer and mark this with the 27 milestone?  thanks

2025-03-11 15:04 UTC, christinerogers commented
welcome back @driusan - this should be merge-ready for you

2025-03-11 15:48 UTC, driusan commented on modules/acknowledgements/php/modules.class.inc
> + * File contains the Modules class.
What is this for? What are acknowledgement modules?

2025-03-11 16:00 UTC, driusan commented on modules/acknowledgements/php/acknowledgementrow.class.inc
> + * @author     Dave MacFarlane <david.macfarlane2@mcgill.ca>
no I'm not.

2025-03-11 16:00 UTC, driusan commented on modules/acknowledgements/php/acknowledgementrow.class.inc
> + * The acknowledgements requires a specific "row" concept because
I don't think this paragraph makes any sense

2025-03-11 16:01 UTC, driusan commented on modules/acknowledgements/php/acknowledgementrow.class.inc
> +     * Create a new HelpRow
This also looks wrong.

2025-03-11 16:01 UTC, driusan commented on modules/acknowledgements/php/acknowledgements.class.inc
> + * File contains the Module_Manager class.
This isn't the Module_manager class either?

2025-03-11 16:02 UTC, driusan requested changes
a lot of the comments on this look completely wrong. Can you review them and make sure they're accurate?

2025-03-11 20:03 UTC, merged