[examiner] Column for 'Instrument' in certification menu appears narrow
aces/Loris pull request #8453
Opened 2023-03-17 14:18 UTC by miladheshmati

## Brief summary of changes

This PR is changing the CSS class used in the examiner page. The former class had a small percentage of the width causing the first field become narrow, by changing it to another class, the problem is solved.

- [x] Have you updated related documentation?

#### Testing instructions (if applicable)

1. Go to the examiner module
2. Select an examiner to access the 'Certification' page
3. Text in the 'Instrument' column should not be narrow anymore.

#### Link(s) to related issue(s)

* Resolves #  #8026

2023-03-24 15:09 UTC, racostas requested changes
Doesn't seem to be working for me.

This is before the change:
![image](https://user-images.githubusercontent.com/37309344/227563964-32a48eae-4425-4882-8323-0902f2b6d6fc.png)

This is after the change:
![image](https://user-images.githubusercontent.com/37309344/227564397-61b47f21-223e-4d41-b048-49f5f8a5cf26.png)

2023-03-27 14:20 UTC, miladheshmati commented
@racostas, ready to be retested.

2023-03-27 15:49 UTC, racostas requested changes
nice!
Just one minor thing. Let's try to give a bit of space between the textboxes and the buttons. 
![image](https://user-images.githubusercontent.com/37309344/227994462-f66a6dfb-d9c3-4554-9584-9c039f56ff15.png)

2023-03-27 16:18 UTC, racostas requested changes
This proposal will be introducing a **"line"** between the textboxes and the buttons. While I'm not strongly  in favor or against it does differs from the original design.  

What do you thing about it @miladheshmati ? Could you please also consult it with Rida and Dave, maybe Christine.  

Thanks. 

![image](https://user-images.githubusercontent.com/37309344/228002030-f44b2884-9e41-4f38-8bdf-df024d214b6d.png)

2023-04-26 15:12 UTC, merged