add missing downloadpath
aces/Loris pull request #8618
Opened 2023-04-12 14:42 UTC by kongtiaowang

## Brief summary of changes

- [ ] Have you updated related documentation?

#### Testing instructions (if applicable)

1.

#### Link(s) to related issue(s)

* Resolves #  (Reference the issue this fixes, if any.)

2023-04-12 15:03 UTC, driusan requested changes

2023-04-12 15:03 UTC, driusan commented on SQL/Cleanup_patches/2023-04-12-add-missing-downloadpath.sql
> +INSERT INTO ConfigSettings (Name, Description, Visible, AllowMultiple, DataType, Parent, Label, OrderNumber) SELECT 'DownloadPath', 'Where files are downloaded', 1, 0, 'text', ID, 'Downloads', 4 FROM
This should already be there. There's no cleanup patch required. According to `git grep` it was added pre-14.10 and I don't see anywhere it was removed. It's also already in the default schema in `SQL/0000-00-03-ConfigTables.sql`.

SQL/Archive/Pre-14.10/2014-09-25-ConfigToDB.sql:INSERT INTO ConfigSettings (Name, Description, Visible, AllowMultiple, DataType, Parent) SELECT 'DownloadPath', 'Where files are downloaded', 1, 0, 'text', ID FROM ConfigSettings WHERE Name="paths";

2023-04-12 15:03 UTC, driusan commented on SQL/Cleanup_patches/2023-04-12-add-missing-downloadpath.sql
> +INSERT INTO Config (ConfigID, Value) SELECT ID, "/var/www/loris" FROM ConfigSettings WHERE Name="DownloadPath";
This doesn't seem like a very good default value to set it to.

2023-05-11 14:34 UTC, kongtiaowang commented
@driusan it has been rebased. it is good to go.

2023-05-11 15:06 UTC, merged