[api] add new integration tests for API project endpoint
aces/Loris pull request #8629
Opened 2023-04-13 15:42 UTC by regisoc

## Brief summary of changes

Add two endpoint integration tests:

- `/projects/{project}/instruments/{instrument}`
- `/projects/{project}/recordings`

#### Link(s) to related issue(s)

* Resolves #8617

2023-04-20 12:58 UTC, kongtiaowang commented on raisinbread/test/api/LorisApiProjectsTest.php
> +    protected $instrumentName = "testtest";
@regisoc please using "aosi" in the test case, or keep the markTestSkipped in this  test case. I will figure out the missing bmi in docker later.

2023-04-20 19:15 UTC, kongtiaowang commented
@regisoc I have added the bmi into testing docker.
add these changes into your PR from https://github.com/aces/Loris/pull/8650.

2023-04-20 19:16 UTC, kongtiaowang commented on raisinbread/test/api/LorisApiProjectsTest.php
> +                $response->getBody()->getContents()
```suggestion
                                strstr(response->getBody()->getContent(),"{")
```

2023-04-20 19:17 UTC, kongtiaowang commented on raisinbread/test/api/LorisApiProjectsTest.php
> +    protected $instrumentName = "aosi";
```suggestion
    protected $instrumentName = "bmi";
```

2023-04-20 19:20 UTC, kongtiaowang commented
instrumentProjectArray will return "
    [Meta] => Array
        (
            [InstrumentVersion] => 1l
            [InstrumentFormatVersion] => v0.0.1a-dev
            [ShortName] => bmi
            [LongName] => BMI Calculator
            [IncludeMetaDataFields] => true
        )

    [Elements] => Array
        (
            [0] => Array
                (
                    [Type] => ElementGroup
                    [GroupType] => Page
                    [Description] => Top
                    [Elements] => Array
                        (
                            [0] => Array
                                (
                                    [Type] => date
                                    [Name] => Date_taken
                                    [Description] => Date of Administration
                                    [Options] => Array
                                        (
                                            [MinDate] => 2006-01-01
                                            [MaxDate] => 2012-12-31
                                        )

                                )

                            [1] => Array
                                (
                                    [Type] => select
                                    [Name] => Examiner
                                    [Description] => Examiner
                                    [Options] => Array
                                        (
                                            [Values] => Array
                                                (
                                                    [] => 
                                                )

                                            [AllowMultiple] => 
                                            [RequireResponse] => 
                                        )

                                )

                            [2] => Array
                                (
                                    [Type] => select
                                    [Name] => unit_classification
                                    [Description] => Choose unit of measurement
                                    [Options] => Array
                                        (
                                            [Values] => Array
                                                (
                                                    [] => 
                                                    [metric] => Metric
                                                    [imperial] => Imperial
                                                )

                                            [AllowMultiple] => 
                                            [RequireResponse] => 
                                        )

                                )

                        )

                )

            [1] => Array
                (
                    [Type] => ElementGroup
                    [GroupType] => Page
                    [Description] => Imperial units
                    [Elements] => Array
                        (
                            [0] => Array
                                (
                                    [Type] => numeric
                                    [Name] => height_feet
                                    [Description] => Your height (feet) :
                                    [Options] => Array
                                        (
                                            [NumberType] => integer
                                            [MinValue] => 
                                            [MaxValue] => 0
                                            [RequireResponse] => 1
                                        )

                                )

                            [1] => Array
                                (
                                    [Type] => numeric
                                    [Name] => height_inches
                                    [Description] => Your height (inches) :
                                    [Options] => Array
                                        (
                                            [NumberType] => integer
                                            [MinValue] => 
                                            [MaxValue] => 0
                                            [RequireResponse] => 1
                                        )

                                )

                            [2] => Array
                                (
                                    [Type] => numeric
                                    [Name] => weight_lbs
                                    [Description] => Your weight (lbs) :
                                    [Options] => Array
                                        (
                                            [NumberType] => integer
                                            [MinValue] => 50
                                            [MaxValue] => 500
                                            [RequireResponse] => 1
                                        )

                                )

                        )

                )

            [2] => Array
                (
                    [Type] => ElementGroup
                    [GroupType] => Page
                    [Description] => Metric Units
                    [Elements] => Array
                        (
                            [0] => Array
                                (
                                    [Type] => numeric
                                    [Name] => height_cms
                                    [Description] => Your height (cms) :
                                    [Options] => Array
                                        (
                                            [NumberType] => integer
                                            [MinValue] => 
                                            [MaxValue] => 0
                                            [RequireResponse] => 1
                                        )

                                )

                            [1] => Array
                                (
                                    [Type] => numeric
                                    [Name] => weight_kgs
                                    [Description] => Your weight (kgs) :
                                    [Options] => Array
                                        (
                                            [NumberType] => integer
                                            [MinValue] => 
                                            [MaxValue] => 0
                                            [RequireResponse] => 1
                                        )

                                )

                        )

                )

            [3] => Array
                (
                    [Type] => ElementGroup
                    [GroupType] => Page
                    [Description] => Results
                    [Elements] => Array
                        (
                        )

                )

        )

)
"

2023-04-20 20:46 UTC, regisoc commented
@kongtiaowang Hi Shen, it seems to work now! At least for the instrument endpoint.
Is the same thing happening with the data for the `/projects/{project}/recordings` endpoint?
This last endpoint is working on my vm through the api_docs, not sure if it is the same issue
![image](https://user-images.githubusercontent.com/25327259/233483798-6efcf41a-5223-44ef-964e-640d8b347599.png)

2023-04-21 12:41 UTC, kongtiaowang requested changes

2023-04-21 12:41 UTC, kongtiaowang commented on raisinbread/test/api/LorisApiProjectsTest.php
> +            "projects/$this->projectName",
```suggestion
            "projects/$this->projectName/recordings",
```

2023-04-24 13:40 UTC, kongtiaowang approved these changes
LGTM

2023-04-25 12:31 UTC, merged