[RB] Fix bmi DB error
aces/Loris pull request #8673
Opened 2023-04-25 18:12 UTC by laemtl

An inconsistency between the linst file and the sql schema in the enum field trigger a 500 error. Fixed by updating the enum with the missing value.

2023-04-25 18:19 UTC, laemtl commented
@zaliqarosli I apply the changes in the test VM to help your tests.

2023-04-25 20:29 UTC, zaliqarosli requested changes

2023-04-25 20:29 UTC, zaliqarosli commented on raisinbread/instruments/bmi.linst
> +table{@}bmi
i think this element now lives in bmi.meta so doesn't need to be here as well

2023-04-25 20:29 UTC, zaliqarosli commented on raisinbread/instruments/instrument_sql/bmi.sql
> +`unit_classification` enum('metric','imperial','standard','not_answered') default NULL,
i think the options should just be metric and imperial so its just the 'standard' in the SQL that needs to be changed to 'imperial'

2023-04-25 20:29 UTC, zaliqarosli commented on raisinbread/instruments/bmi.linst
> +numeric{@}height_feet{@}Your height (feet) :{@}undefined{@}undefined
i think this 'undefined' might be coming from a bug in the instrument builder? unless this is the max/min in which case i think leaving it blank should be better. not sure if 'undefined' case is being handled in the NDB_BVL_Instrument_LINST class

2023-04-26 16:20 UTC, laemtl commented
@zaliqarosli Ready for second review

2023-04-26 17:02 UTC, zaliqarosli requested changes
i think changes to `raisinbread/instruments/bmi.linst` can be removed completely cz its just a permissions change which i think is unnecessary

2023-04-26 17:25 UTC, laemtl commented
Yes, the 400 should fo away once #8651 is merged. I fixed the perm change, thanks for the hint :)

2023-04-26 18:21 UTC, laemtl commented
New error fixed in #8681

2023-04-26 19:37 UTC, zaliqarosli approved these changes

2023-05-02 13:20 UTC, merged