[Config] imaging and eeg config groups
aces/Loris pull request #8685
Opened 2023-05-01 16:45 UTC by laemtl

- create imaging and eeg config groups
- add new config EEGS3DataPath

2023-07-03 13:32 UTC, regisoc reviewed
Tested. 

![image](https://github.com/aces/Loris/assets/25327259/7c087fbd-c3d0-400b-b0e5-1c8162cb8183)

@laemtl Should we add these changes in `SQL/0000-00-03-ConfigTables.sql`?

Else LGTM.

2023-12-05 22:12 UTC, regisoc commented on SQL/0000-00-03-ConfigTables.sql
> +INSERT INTO ConfigSettings (Name, Description, Visible, AllowMultiple, DataType, Parent, Label, OrderNumber) SELECT 'MINCToolsPath', 'Path to the MINC tools', 1, 0, 'web_path', ID, 'Path to the MINC
Is order important here? 
![image](https://github.com/aces/Loris/assets/25327259/062c70be-c9db-452f-87e1-cf3eef2f020d)

2023-12-12 16:27 UTC, laemtl commented on SQL/New_patches/2023-05-01-imaging-eeg-configs.sql
> +-- Add the EEG Pipeline Config group
<img width="344" alt="Screenshot 2023-12-12 at 11 27 29 AM" src="https://github.com/aces/Loris/assets/32041423/b0da5167-9d55-4115-895e-e9bdf09a3431">

2023-12-12 16:28 UTC, laemtl commented on SQL/New_patches/2023-05-01-imaging-eeg-configs.sql
> +-- Add the EEG Pipeline Config group
I think it was :)

2023-12-12 18:58 UTC, regisoc commented on SQL/0000-00-03-ConfigTables.sql
> +INSERT INTO ConfigSettings (Name, Description, Visible, AllowMultiple, DataType, Parent, Label, OrderNumber) SELECT 'MINCToolsPath', 'Path to the MINC tools', 1, 0, 'web_path', ID, 'Path to the MINC
After discussion, looks like it is not.

2023-12-12 19:07 UTC, regisoc approved these changes

2023-12-12 19:46 UTC, driusan commented
Tests are failing. Looks like there might be an SQL error introduced in the default schema?

2023-12-12 21:37 UTC, regisoc commented on SQL/0000-00-03-ConfigTables.sql
>  INSERT INTO ConfigSettings (Name, Description, Visible, AllowMultiple, DataType, Parent, Label, OrderNumber) SELECT 'EEGUploadIncomingPath', 'Path to the upload directory for incoming EEG studies', 1
duplicated line

2023-12-12 21:37 UTC, regisoc commented on SQL/0000-00-03-ConfigTables.sql
> +INSERT INTO ConfigSettings (Name, Description, Visible, AllowMultiple, DataType, Parent, Label, OrderNumber) SELECT 'EEGUploadIncomingPath', 'Path to the upload directory for incoming EEG studies', 1
duplicated line

2023-12-12 21:42 UTC, regisoc commented
Duplicated lines L78 and L182 in configTables.sql

2023-12-12 21:44 UTC, regisoc requested changes
Duplicated lines L78 and L182 in configTables.sql

2023-12-19 19:55 UTC, regisoc approved these changes

2024-01-11 14:08 UTC, merged