[Timepoint List] Hide visits that are from user unaffiliated projects
aces/Loris pull request #8723
Opened 2023-06-02 18:34 UTC by skarya22

## Brief summary of changes

- [N/A] Have you updated related documentation?

#### Testing instructions (if applicable)

1. Create a timepoint for a candidate for another project
2. Look at the candidate with a user that does not have permissions to that project
3. You should not see that timepoint
4. Confirm that visits with user affiliated projects do not disappear as well

#### Link(s) to related issue(s)

* Resolves #8710  (Reference the issue this fixes, if any.)

#### Example with user who does not have access to project Challah
**Before:**
<img width="952" alt="image" src="https://github.com/aces/Loris/assets/51128536/5b67db6e-4652-4254-92de-324dcee65c5e">
**After:** 
<img width="964" alt="image" src="https://github.com/aces/Loris/assets/51128536/b09dc2a6-53a2-4fe7-85aa-8c38ec0a4bc0">

2023-06-09 22:03 UTC, zaliqarosli requested changes

2023-06-09 22:03 UTC, zaliqarosli commented on modules/timepoint_list/php/timepoint_list.class.inc
> +                    && $user->hasProject($timePoint->getProjectID());
hey @skarya22 i saw that you changed the description of the issue I created about this bug (https://github.com/aces/Loris/issues/8710). your modification is wrong. the fix needs to happen on candidate_profile module, not timepoint_list. the timepoint_list is working as should, and candidate_profile needs to mimic the same, but doesnt

2023-06-13 19:34 UTC, skarya22 commented
@zaliqarosli after our discussion, I found the error in timepoint_list causing users with the "all sites" permission access to profiles from other projects and removed that.
candidate_profile did not need any changes.

2023-06-14 17:55 UTC, driusan commented
@zaliqarosli I think this is back in your court.

2023-06-14 18:23 UTC, zaliqarosli requested changes
@skarya22 can you add this intended case to the Test Plan?

2023-06-14 19:04 UTC, zaliqarosli requested changes

2023-06-14 19:52 UTC, zaliqarosli requested changes
let's keep it simple and not mention any permissions as they don't apply here

2023-06-14 19:52 UTC, zaliqarosli commented on modules/candidate_profile/test/TestPlan.md
> +5. Ensure that you cannot see visits from projects that you are not affiliated with. This behaviour is still expected when you have permission `access_all_profiles`.
```suggestion
5. Ensure that you can always only see visits from projects that you are affiliated with.
```

2023-06-15 14:57 UTC, zaliqarosli commented
you need to modify the other test plan too

2023-06-15 16:12 UTC, merged