Fix candidate_parameters permission problem
aces/Loris pull request #8734
Opened 2023-06-07 14:23 UTC by sanjay-thiyagarajan

## Brief summary of changes
Remove unnecessary access_profiles permission check

#### Testing instructions

1. Login with a user account without candidate_parameters permission.
2. Try accessing the URL of candidate profile of any candidate obtained from the admin account.
3. You should be able to see a permission denied note on the screen.

#### Link(s) to related issue(s)

* Resolves #8733

2023-06-07 17:20 UTC, driusan commented
I'm not sure I understand why this is being removed, but I'll comment on the issue instead of here..

2023-06-08 14:01 UTC, racostas commented
> I'm not sure I understand why this is being removed, but I'll comment on the issue instead of here..

Hi @driusan, I commented in the original issue.

2023-06-13 15:30 UTC, zaliqarosli requested changes
remove comment to match code change

2023-06-13 15:30 UTC, zaliqarosli commented on modules/candidate_parameters/php/candidate_parameters.class.inc
>          // one of the candidate_parameter permissions AND have the candidate's site.
```suggestion
        // User must one of the candidate_parameter permissions AND have the candidate's site.
```

2023-06-15 14:17 UTC, zaliqarosli commented
@sanjay-thiyagarajan i can approve this after you fix php lint. and then @racostas would you be able to test it as you reported the bug?

2023-06-15 14:22 UTC, zaliqarosli commented
this is related: https://github.com/aces/Loris/issues/8701, https://github.com/aces/Loris/pull/8725

2023-06-16 15:18 UTC, zaliqarosli commented
@driusan does this need to go to 25 or 24.1?

2023-06-16 16:13 UTC, zaliqarosli commented
@sanjay-thiyagarajan can you rebase this to 25.0-release branch and push it there?

2023-06-16 16:43 UTC, racostas commented
He will do it !! Thank you @zaliqarosli and @driusan

2023-06-17 14:16 UTC, sanjay-thiyagarajan commented
Creating a new one for merging into 25.0-release

2023-06-17 14:16 UTC, closed without merging

2023-06-19 15:50 UTC, zaliqarosli commented
replaced by https://github.com/aces/Loris/pull/8793