[mri_violations] Update Help
aces/Loris pull request #8772
Opened 2023-06-12 16:02 UTC by skarya22

## Brief summary of changes

- Updated the help content of mri_violations to be a bit more clear

* Resolves #8737

2023-07-04 17:24 UTC, driusan commented
@zaliqarosli can you review

2023-07-04 21:13 UTC, zaliqarosli requested changes

2023-07-04 21:13 UTC, zaliqarosli commented on modules/mri_violations/help/mri_violations.md
> +In-order to see the details of a SeriesUID problem, press the "Could not identify scan type" or "Protocol violation" link in the Type of Problem column.
```suggestion
Clicking "Could not identify scan type" or "Protocol violation" links in the *Type of Problem* column will display a popup with the details of any problems for that SeriesUID.
```

2023-07-05 16:35 UTC, zaliqarosli approved these changes

2023-07-05 16:42 UTC, merged