[issue_tracker] Do not display inactive users in issue form
aces/Loris pull request #8841
Opened 2023-07-19 15:12 UTC by charlottesce

## Brief summary of changes
Inactive users are not displayed in dropdowns to assign / watch an issue

#### Testing instructions (if applicable)
1. Go to Tools -> Issue Tracker
2. Make a new issue / edit an existing one -> ensure you don't see any inactive user in the "Assignee" nor "Add others to watching" dropdowns

#### Note

This is a CCNA override - https://github.com/aces/CCNA/pull/4100

2023-08-10 14:55 UTC, CamilleBeau requested changes
This is working well! I am however wondering now if we should also not display users that have Pending_approval='Y'?

2023-08-10 14:55 UTC, CamilleBeau commented on modules/issue_tracker/php/edit.class.inc
> +                "SELECT Real_name, UserID FROM users WHERE Active='Y'",
And so on and so forth for the other changes here
```suggestion
                "SELECT Real_name, UserID FROM users WHERE Active='Y' AND Pending_approval='N'",
```

2023-08-10 15:37 UTC, CamilleBeau requested changes
As per Dave's request, can we add the assignee / watchers that are currently assigned to the issue to the drop down even if they are inactive? Should be simple to do with a join on issues using issueID from $values, and an OR statement

2023-08-14 14:03 UTC, charlottesce commented
Two other changes have been added as bug fixes I noticed during testing: 
1. Added a getBreadcrumbs function for the edit class, otherwise we get the following error when clicking on the 'Issue' link of the path on the top left of the page, as it links to 'issue_tracker/issue' which doesn't exist.
![image](https://github.com/aces/Loris/assets/75381352/f5262104-9b45-49b8-bfe5-a760dc359f03)

2. The updateComments function of the edit class can now take a null value as input, otherwise if someone tries to update an issue without adding a comment, a PHP error is raised that updateComments expects a string while null is given.

2023-10-24 19:24 UTC, CamilleBeau approved these changes

2023-10-24 19:24 UTC, CamilleBeau commented
Working well!

2023-11-07 18:30 UTC, merged