[issue_tracker] Resolves special characters in titles
aces/Loris pull request #8842
Opened 2023-07-19 15:52 UTC by charlottesce

## Brief summary of changes
Resolves how special characters were appearing encoded in the title in the filterable table and the title of the issue itself e.g. `&amp;, &quot;, etc.` instead of `&, ", etc.`

#### Testing instructions (if applicable)

1. Go to Tools -> Issue Tracker
2. Create a new issue and put the special characters `&, <, >, "` in the title; fill out necessary fields -> click Submit 
a. In the main page, the title of the issue in the table should have the characters above as is, and not "`&amp;`", etc. 
3. Click to Edit the issue you just created
a. In the edit form, the title of the issue in the table should again have the characters above, and not "`&amp;`", etc. 

#### Note

This is a CCNA override - https://github.com/aces/CCNA/pull/4032, https://github.com/aces/CCNA/pull/4084

2023-08-10 14:59 UTC, regisoc approved these changes
Tested. LGTM.

2023-08-10 15:07 UTC, ridz1208 requested changes
no no no no no no no no no no no

2023-08-10 15:21 UTC, ridz1208 commented
@charlottesce The current solution is only masking the fact that the data is encoded for security but never decoded. The real solution here is that we simply no longer need to encode the data and should instead be saving it with unsafeupdate and unsafeinsert instead.

see my comments on the lines

2023-08-11 12:05 UTC, ridz1208 approved these changes
bellissimo !

@driusan please double check the security risk

2023-08-15 15:17 UTC, driusan commented
do we need an unescaping script to fix existing data?

2023-08-16 14:18 UTC, merged