[datadict] Add subprojects filter options
aces/Loris pull request #8844
Opened 2023-07-19 19:46 UTC by charlottesce

## Brief summary of changes

This PR adds subprojects as filter options in the data dictionary. 
A user should only see subprojects from the project(s) that they have permission to.

#### Testing instructions (if applicable)

1. Go to Tools -> Data Dictionary
2. Make sure you can see a subproject selection box, with only subprojects from projects your user has permission to as options
3. Make sure that the subprojectIDs link properly onto the subproject titles in the inspect element. 
4. Test that subprojects generally link to the correct instruments.

#### Note

This is a CCNA override - https://github.com/aces/CCNA/pull/6332

2023-08-10 15:38 UTC, ridz1208 requested changes

2023-08-10 15:38 UTC, ridz1208 commented on modules/datadict/php/datadict.class.inc
> +
this code section is already repeated twice in this PR. we should find a way to reduce duplication

2023-08-10 15:38 UTC, ridz1208 commented on modules/datadict/php/datadictrowprovisioner.class.inc
> +            LEFT JOIN test_battery tb ON pt.sourceFrom=tb.Test_name
@driusan doesnt like this

2024-02-07 14:51 UTC, regisoc commented
@ridz1208 does this PR still need work/discussion?

2024-07-02 14:30 UTC, ridz1208 commented on modules/datadict/php/datadictrowprovisioner.class.inc
> +            LEFT JOIN test_battery tb ON pt.sourceFrom=tb.Test_name
@ridz1208 doesn't remember what this comment is about

2024-10-28 14:32 UTC, skarya22 commented
Closing as old duplicate of override in #9390

2024-10-28 14:32 UTC, closed without merging