[instrument_manager] Fixing error in generate_tables_sql_and_testNames tool
aces/Loris pull request #9157
Opened 2024-03-21 16:02 UTC by AlexandraLivadas

The `tools/generate_tables_sql_and_testNames.php` script is causing an error when uploading a new instrument using the Instrument Manager module. Since the output string was being reset to empty within the for-loop, the "Create Table" statement was not properly generated. 

#### Testing instructions

1. Go to the instrument manager module and try uploading the `/test/instruments/test_all_fields.linst` file
2. Check that there is a success message and that the project folder and database are correctly updated with the new instrument.

2024-03-21 16:07 UTC, laemtl approved these changes

2024-03-21 16:08 UTC, laemtl requested changes
Tests are failing :(
You gave a typo here:
$output = "":    ->    $output = "";

2024-03-21 16:12 UTC, laemtl approved these changes

2024-03-26 19:19 UTC, merged

2024-03-26 19:20 UTC, driusan commented
I'm assuming there's no related issue this should close?