[Publication] Fix for auto-selecting Project in edit
aces/Loris pull request #9187
Opened 2024-03-28 19:17 UTC by skarya22

## Brief summary of changes

- The value expected by the field is the number id, but the fetch statement was returning the name - so I modified the sql statement to fetch the project ID.

#### Testing instructions (if applicable)

1. Propose a new project in the publication module and remember the project name
2. Submit and then go back to the main module and select it and make sure the project is auto selected

#### Link(s) to related issue(s)

* Resolves #9134  (Reference the issue this fixes, if any.)

2024-04-08 14:27 UTC, jeffersoncasimir requested changes
This fixes the issue as described. The project no longer seems "unassigned" when _Editing_.

However, this solution introduces an issue where  when _Viewing_ a project, the ID is displayed instead of the name:

<img width="826" alt="Screenshot 2024-04-08 at 10 20 06 AM" src="https://github.com/aces/Loris/assets/15801528/3038f75b-c0ac-4775-b62c-0f8c432c6124">

2024-04-16 14:18 UTC, skarya22 commented
@jeffersoncasimir thank you for catching that. I have fixed it to work in edit, viewing, and submitting a new publication.

2024-04-16 14:39 UTC, jeffersoncasimir approved these changes

2024-04-16 14:39 UTC, jeffersoncasimir commented
Works as expected!

2024-04-16 16:48 UTC, merged