[timepoint_list] edit / archive IBIS - features
aces/Loris pull request #9238
Opened 2024-05-06 14:03 UTC by kongtiaowang

## Brief summary of changes

[timepoint_list] archive feature
![截屏2024-05-06 上午10 01 40](https://github.com/aces/Loris/assets/9876007/5f377f2c-b27b-4e8a-b45b-8fea1bd6d89b)
![截屏2024-05-06 上午10 01 46](https://github.com/aces/Loris/assets/9876007/407f5a61-cdf9-411c-b065-487d77ce2b53)
test:
if a user has the candidate_edit permission, the [edit and achive] buttons will show on the frontend page. 
click edit button will re-edit the subproject and start date.
click archive button will archive a visit time point.

2024-10-01 14:12 UTC, cmadjar commented
@kongtiaowang does this PR still needs work or the label can be removed?

@GeorgeMurad could you review/test this PR once Shen confirms it is ready for review?

Thanks!

2024-11-28 15:28 UTC, kongtiaowang commented
@GeorgeMurad it is ready to review and test.

2024-11-28 16:03 UTC, GeorgeMurad approved these changes
LGTM

2025-02-04 15:23 UTC, driusan commented on modules/timepoint_list/php/timepoint_list.class.inc
> +                $method = $request->getMethod();
not a blocker, but it would be cleaner to write this as a switch

2025-02-04 15:24 UTC, driusan commented on modules/timepoint_list/php/timepoint_list.class.inc
> +        $DB = \NDB_Factory::singleton()->database();
this should use $this->loris->getDatabaseConnection()

2025-02-04 15:27 UTC, driusan commented on modules/timepoint_list/php/timepoint_list.class.inc
> +        if (is_array($jsonBody) && array_key_exists('sessionID', $jsonBody)) {
I think you're better off checking if it's not set and returning an error, then retrieving the value and getting it.

Otherwise you're still running the update session with a value of `ID=null` in the where clause. I don't think it will ever affect any rows since the ID is a primary key, but it still seems like a dangerous assumption to make if the code changes in a way that something else happens here.

2025-02-04 15:27 UTC, driusan commented on modules/timepoint_list/php/timepoint_list.class.inc
> +        // Check if $jsonBody is an array before accessing its keys
should return an error if not?

2025-02-04 15:28 UTC, driusan commented on modules/timepoint_list/php/timepoint_list.class.inc
> +            $DB = \NDB_Factory::singleton()->database();
$this->loris->getDatabaseConnection

2025-02-04 15:31 UTC, driusan requested changes
See comments

2026-07-30 13:56 UTC, kongtiaowang commented
will send a new one.

2026-07-30 13:56 UTC, closed without merging