[dataquery] Add ability to retrieve results of previous run from API
aces/Loris pull request #9301
Opened 2024-06-20 14:01 UTC by driusan

This implements the endpoint that is listed as "aspirational" in the
dataquery api schema to load the results of a previously run query.

It was originally left out for fear of performance issues but with
this implementation performance seems to be comparable to without
it.

This does not implement a frontend to reload query results, but
the API functionality is useful for i.e. api callbacks that want
to process the results of a query without the need to re-run
it (and the possibility to get different results.)

2024-06-20 14:01 UTC, driusan commented on modules/dataquery/php/endpoints/queries/query/run.class.inc
> +                    /* @phan-suppress-next-line PhanUnusedClosureParameter */
Closure signature needs to match the callback of DataIteratorBinaryStream, so the unused parameter can't be removed.

2024-06-20 14:03 UTC, driusan commented on modules/dataquery/php/endpoints/queries/query/run/run.class.inc
> +        // FIXME: Check permissions. Check if count(*) > 0.
Sent as a draft until the permissions checks are added, but otherwise the rest of this PR should be ready to be reviewed or tested.

2024-10-29 15:08 UTC, CamilleBeau commented
@driusan needs to have the conflict resolved but otherwise this is working well!

2025-01-22 16:07 UTC, CamilleBeau requested changes
Running a query from this PR isn't working. Getting the following error:

> [Wed Jan 22 11:00:02.344866 2025] [php:error] [pid 7561] [client ::1:42036] PHP Fatal error:  Uncaught TypeError: LORIS\\dataquery\\QueryRun::getCandidates(): Return value must be of type array, Generator returned in /var/www/loris/modules/dataquery/php/queryrun.class.inc:103\nStack trace:\n#0 /var/www/loris/modules/dataquery/php/querydataprovisioner.class.inc(51): LORIS\\dataquery\\QueryRun->getCandidates()\n#1 /var/www/loris/src/Data/ProvisionerInstance.php(116): LORIS\\dataquery\\QueryDataProvisioner->getAllInstances()\n#2 /var/www/loris/modules/dataquery/php/querydataprovisioner.class.inc(41): LORIS\\Data\\ProvisionerInstance->execute()\n#3 /var/www/loris/modules/dataquery/php/endpoints/queries/query/run.class.inc(70): LORIS\\dataquery\\QueryDataProvisioner->execute()\n#4 /var/www/loris/modules/dataquery/php/endpoints/queries/query/run.class.inc(47): LORIS\\dataquery\\endpoints\\queries\\query\\Run->runQuery()\n#5 /var/www/loris/src/Middleware/Compression.php(36): LORIS\\dataquery\\endpoints\\queries\\query\\Run->handle()\n#6 /var/www/loris/modules/dataquery/php/queries.class.inc(83): LORIS\\Middleware\\Compression->process()\n#7 /var/www/loris/src/Middleware/UserPageDecorationMiddleware.php(248): LORIS\\dataquery\\Queries->handle()\n#8 /var/www/loris/src/Middleware/PageDecorationMiddleware.php(59): LORIS\\Middleware\\UserPageDecorationMiddleware->process()\n#9 /var/www/loris/php/libraries/NDB_Page.class.inc(726): LORIS\\Middleware\\PageDecorationMiddleware->process()\n#10 /var/www/loris/php/libraries/Module.class.inc(322): NDB_Page->process()\n#11 /var/www/loris/src/Middleware/ResponseGenerator.php(51): Module->handle()\n#12 /var/www/loris/src/Middleware/AuthMiddleware.php(64): LORIS\\Middleware\\ResponseGenerator->process()\n#13 /var/www/loris/src/Router/ModuleRouter.php(75): LORIS\\Middleware\\AuthMiddleware->process()\n#14 /var/www/loris/src/Middleware/ExceptionHandlingMiddleware.php(55): LORIS\\Router\\ModuleRouter->handle()\n#15 /var/www/loris/src/Router/BaseRouter.php(138): LORIS\\Middleware\\ExceptionHandlingMiddleware->process()\n#16 /var/www/loris/src/Middleware/ResponseGenerator.php(51): LORIS\\Router\\BaseRouter->handle()\n#17 /var/www/loris/src/Middleware/ContentLength.php(53): LORIS\\Middleware\\ResponseGenerator->process()\n#18 /var/www/loris/htdocs/index.php(74): LORIS\\Middleware\\ContentLength->process()\n#19 {main}\n  thrown in /var/www/loris/modules/dataquery/php/queryrun.class.inc on line 103, referer: http://localhost:8080/dataquery/

2025-01-22 18:13 UTC, driusan commented
@CamilleBeau I fixed the error (and a couple other introduced by the rebase). Should be ready now.

2025-01-22 19:11 UTC, CamilleBeau reviewed
Running a query, saving a query, filters, and accessing previous queries from API are all working now. 

Just a couple of notes on the code

2025-01-22 19:11 UTC, CamilleBeau commented on modules/dataquery/php/endpoints/queries/query/run.class.inc
> +        set_time_limit(300);
Should this be configurable?

2025-01-22 19:11 UTC, CamilleBeau commented on modules/dataquery/php/endpoints/queries/query/run.class.inc
> +                if ((count($values) >= 2000 || $end) && count($values) > 0) {
Also wondering if this value should be configurable - why 2000?

2025-01-22 19:11 UTC, CamilleBeau commented on modules/dataquery/php/endpoints/queries/query/run.class.inc
> +        //->withHeader("Content-Type", "application/octet-stream")
Should this be removed?

2025-01-22 19:11 UTC, CamilleBeau commented on modules/dataquery/php/endpoints/queries/query/run/run.class.inc
> +        // FIXME: Check permissions. Check if count(*) > 0.
Permission check needed still?

2025-01-22 19:11 UTC, CamilleBeau commented on modules/dataquery/php/endpoints/queries/query/run/run.class.inc
> +                //->withHeader("Content-Type", "application/octet-stream")
This looks like it can be removed

2025-01-22 19:15 UTC, driusan commented on modules/dataquery/php/endpoints/queries/query/run.class.inc
> +                if ((count($values) >= 2000 || $end) && count($values) > 0) {
It is arbitrary but I don't think it needs to be configurable.. the goal is to break it up into chunks so that the insert is done in batches but the SQL query string doesn't grow without bound for large queries. 2000 comes from trial and error.

2025-01-22 19:24 UTC, driusan commented on modules/dataquery/php/endpoints/queries/query/run.class.inc
> +        set_time_limit(300);
Maybe?

I think it can just be removed. Our documentation says to set `max_execution_time` to 10800 to support large files which is the php config setting that php would fall back on.

https://acesloris.readthedocs.io/en/latest/docs/wiki/00_SERVER_INSTALL_AND_CONFIGURATION/02_Website_Configuration/Handling_Large_File_Uploads.html

2025-01-22 19:53 UTC, driusan commented on modules/dataquery/php/endpoints/queries/query/run/run.class.inc
> +        // FIXME: Check permissions. Check if count(*) > 0.
Oops.. you're right. That's still needed.

2025-01-22 20:32 UTC, driusan commented on modules/dataquery/php/endpoints/queries/query/run/run.class.inc
> +        // FIXME: Check permissions. Check if count(*) > 0.
Done

2025-01-27 21:11 UTC, CamilleBeau approved these changes
All the tests I ran are passing now for the saved queries accessed from API, running queries, saving queries, and accessing queries / data from a user with limited access. One thing to note is that you can have access to another user's private query using the API URL as long as you have the access to all of the fields in the query. If this is intended then all looks good!

2025-02-04 15:20 UTC, merged