[issue_tracker] Introduce Rejected status & Medications category
aces/Loris pull request #9391
Opened 2024-10-07 17:07 UTC by skarya22

## Brief summary of changes

- Add Rejected status to issue tracker. Only someone with `Can re-assign issues, mark issues as closed, comment on all, edit issues.` permission can change the status to this. 

#### Testing instructions (if applicable)

1. When creating an issue, make sure that the rejected status option only appears if you have the permission: 'Can re-assign issues, mark issues as closed, comment on all, edit issues.'
2. Repeat with editing an issue

[CCNA OVERRIDE PR](https://github.com/aces/CCNA/pull/4045)

2024-10-08 14:58 UTC, cmadjar commented
@skarya22 tests are failing. could you fix them?

2024-10-08 15:53 UTC, skarya22 commented on raisinbread/RB_files/RB_issues_categories.sql
> +INSERT INTO `issues_categories` (`categoryID`, `categoryName`) VALUES (16,'Medications');
Thanks!

2024-12-04 20:27 UTC, GeorgeMurad approved these changes
LGTM

2024-12-10 17:40 UTC, driusan requested changes
The "rejected" status makes sense but the "Medications" category seems project specific and doesn't require any code changes. It's just a config from a config table that doesn't require any overrides. can you remove it from this pr?

2026-06-11 15:51 UTC, merged