[image_qc] fix module to display only data affliated to user's site a…
aces/Loris pull request #9399
Opened 2024-10-10 15:24 UTC by shonibare

…nd project

Fixes #6591

**To Test**

1. Create a user with the following permission only:
> Imaging Quality Control: View Flagged Imaging Entries

Make sure not to include `View all-sites Imaging Browser pages` or any other permissions
2. Assign the user site e.g "Ottawa" and project "Pumpernickel"
3. Log in as this user, and navigate to the imaging quality control module
4. Observe that the front page loads with data pertaining only to the user site and project  
5. Observe that the `site` filter only allows filtering only to the user's site
6. Observe that the `project` filter allows filtering only to the user's project

2024-10-31 14:53 UTC, skarya22 commented
My user with Challah and Rome could see scans from other projects
![image](https://github.com/user-attachments/assets/fceb9715-68e2-4ed5-ae11-920d227e5cad)

2024-10-31 14:53 UTC, skarya22 requested changes
Please fix so that scans from projects the user does not have do not show.

2024-11-04 21:18 UTC, skarya22 approved these changes
Looks good!

2024-11-07 16:08 UTC, driusan commented
If a user has sites A, B, and C and a candidate has sites C, and D, my understanding of this change is that it will make it so that the user sees the candidate but it only shows it as having site "C". Is that correct?

If so, I think it should be discussed at a LORIS meeting.

2024-11-07 16:25 UTC, shonibare commented
> If a user has sites A, B, and C and a candidate has sites C, and D, my understanding of this change is that it will make it so that the user sees the candidate but it only shows it as having site "C". Is that correct?
> 
> If so, I think it should be discussed at a LORIS meeting.

@driusan Yes, you are right. The page should only display data from the sites and projects to which the user has access, as well as the site and project filters as reported in the issue.

2025-03-10 15:32 UTC, merged