Escape `LorisForm` value in HTML
aces/Loris pull request #9419
Opened 2024-10-23 21:12 UTC by maximemulder

The `LorisForm` class contains an XSS vulnerability as it can paste data from the GET parameters directly into the HTML.

The `getValue` function reads the GET parameters, but it is used to code unrelated to the HTML, therefore the escape should be done at the call site, not in the function directly. There may be a risk of double escape as `getValue` can get its value from other sources.

Having now looked a the code, I agree that we should get rid of `LorisForm`, building HTML as strings directly (and with so many layers of indirection) is a practice that is 15~20 years old and completely unmaintainable with regards to modern web practices.
 
 Testing: Not tested (which page should I try ?).

2024-10-24 17:24 UTC, maximemulder commented
Yeah, yeah, I saw the CI errors, haven't had time to tackle them yet no need to remind me 😅 (although I probably should have set the PR as a draft until the errors are resolved, my mistake on that).

2024-10-25 16:11 UTC, ridz1208 commented
just adding this for history https://github.com/aces/Loris/pull/6223

2025-01-06 19:50 UTC, racostas approved these changes
Manually tested in Loris RB instruments (including .linst instruments) and some of CCNA (mostly php instruments). This PR seems to work. Not an expert in security myself, the new changes don't seems to break LORIS at the time that add an extra layer of security. 
Don't expert in security myself I cannot warranty this changes will protect for the XSS attacks.

2025-01-06 20:12 UTC, racostas commented
I don think we do have this issue with the double enconding.
![image](https://github.com/user-attachments/assets/abe5451d-0ee0-40e1-96a3-4b8468dd25cb)

2025-01-06 20:16 UTC, racostas requested changes
The issue with the double encoding do seems to be present.

2025-01-14 19:12 UTC, racostas commented
My findings so far after some investigation/discussions:

The function that was used does provide a way to avoid double encoding setting `double_encode` to false.
```
htmlspecialchars(
    string $string,
    int $flags = ENT_QUOTES | ENT_SUBSTITUTE | ENT_HTML401,
    ?string $encoding = null,
    bool $double_encode = true
): string
```
This is maybe not an ideal solution but after seems other alternatives it does looks an appropriate one for this case. This are the seems I took in consideration so far ( I could be missing things nevertheless):

- If we try to track all possible path from with data is goin into the database and use **unsafeupdate** in place of the "safe" version we risk not only to miss someone but also that in the future a change could be made and forget to escape the HTLM first then we could ended up having the "bad code" in the database.

- I tested setting this to false and the issue for the double encoding was not longer present when manually tested. 

- The only case I could think this would be a problem is if the user do intend to enter a special character on purpose. Which it don't seem it would be a use case for our specific system.

This are my my thought so far @maximemulder, @ridz1208 and @driusan . We can talk a bit more "in person" in the PR meeting next Monday.

2026-05-11 19:27 UTC, regisoc commented
Is it resolved with #9557? @maximemulder

2026-06-08 18:41 UTC, CamilleBeau commented
@maximemulder Can you confirm that this PR is already resolved by the PR linked by Regis?

2026-09-08 06:43 UTC, MaximeBICMTL commented
Can confirm that #9557 fixes the issue while preventing double-encoding. Closing as superceded.

2026-09-08 06:43 UTC, closed without merging