[issue_tracker] Convert batch/normal mode toggle to tabs and implement permission control
aces/Loris pull request #9434
Opened 2024-10-29 21:47 UTC by ay-bh

## Brief summary of changes
- Replaced the view toggle button with a tabbed interface using `Tabs` component
- Added permission check to show Batch Edit tab only for users with `issue_tracker_developer` permission
- Implemented data refresh when switching back to Browse Issues tab

#### Testing instructions
1. Login as a user without `issue_tracker_developer` permission - verify only "Browse Issues" tab is visible
2. Login as a user with `issue_tracker_developer` permission - verify both "Browse Issues" and "Batch Edit" tabs are visible
3. Make changes in Batch Edit mode, then switch back to Browse Issues - verify data refreshes automatically

#### Link(s) to related issue(s)
* Resolves #9422, #9423 
* Part of #9418 

#### Screenshot
<img width="1438" alt="image" src="https://github.com/user-attachments/assets/f846d887-6cb1-4ca9-90d3-a9637264156f">

2024-10-30 15:23 UTC, christinerogers approved these changes
lgtm.  

@ay-bh confirm pls this doesn't create bottlenecks by loading all the data in both tabs at once, correct? 

as a future enhancement we could consider hiding the `Browse Issues` tab for non-developers - the vertical space use doesn't make sense if it's the only tab option for end-users.  @regisoc @racostas any strong feelings here?

2024-10-31 15:47 UTC, regisoc requested changes
Thanks @ay-bh !
- PR rebase required.
- This looks clean. I like it.
- @christinerogers Agreed, tabs should be hidden for someone not having the right permission i.e. this could be completely hidden:

![image](https://github.com/user-attachments/assets/a65db0ae-6f83-4542-8b93-5417106f3604)

2024-11-05 14:43 UTC, racostas approved these changes
LGTM.

1. Tested with various uses/permissions looks good to me.
2. The tabs yet appear when the user have only the permission "not developer" but I think this is more cosmetic and should not stop us form merging this one 
![image](https://github.com/user-attachments/assets/1b6b0ab8-7beb-43fe-9c2c-59de5085e5d5)

What do you think @regisoc , @christinerogers ?

2024-11-05 15:04 UTC, regisoc commented
@racostas that is a cosmetic change, we can change it later.

2024-11-05 16:17 UTC, christinerogers commented
> @racostas that is a cosmetic change, we can change it later.

We're all agreed this is good to go, so I've just added this item under `Second followups ` within #9418 PR description. 

Ready for your review @driusan

2024-11-07 14:51 UTC, regisoc approved these changes
@christinerogers just to confirm.

2024-11-07 15:39 UTC, christinerogers commented
3 approvals - over to @driusan for final review.   
Ideally we could get this merged during this final GSOC submission week ending Nov. 8

2024-11-07 16:14 UTC, merged