[Cleanup] Make DBRowProvisioner use Database class
aces/Loris pull request #9509
Opened 2024-12-12 17:58 UTC by driusan

This updates DBRowProvisioner to remove the strval (and fixes #9335).

After doing that, it became clear that the inner class could be replaced by a generator while still fulfilling the contract of returning a `\Traversable`. Doing this made it more obvious that since #9334, pselect could be used directly while maintaining the lazy evaluation instead of bypassing the Database object to use the PDO directly. However this required injecting a `LorisInstance` object to the constructor to get the database connection.

With access to the `LorisInstance` object, the `DBRowProvisioner` can also get a new database connection and disable query buffering to lazily retrieve rows since PR #9344. This may theoretically improve performance and memory usage on large provisioners but has not been tested. (Performance did not decrease in raisinbread but it is not a large dataset where it would be noticeable.)

2024-12-12 18:00 UTC, driusan commented on php/libraries/TimePoint.class.inc
> -        $traversable = (new \LORIS\Data\Table())
This part didn't seem to be useful, so I verified and removed while testing.

2024-12-12 19:20 UTC, driusan commented on modules/battery_manager/test/BatteryManagerTest.php
> -            '2 rows'
This test was failing and when I investigated I don't see any rows with a value of "0" in RB and nothing inserted from the test, so I'm not sure where "2" was coming from and I think it's an error.

2024-12-13 21:06 UTC, skarya22 requested changes

2024-12-13 21:16 UTC, driusan commented on php/libraries/TimePoint.class.inc
> +        return iterator_to_array($provisioner->execute($user));
You are right. I originally didn't have the iterator_to_array and it was working but then I had to include it to get the phan (or phpstan, can't remember) tests to pass. It's probably kind of pointless now.

2024-12-13 21:17 UTC, driusan commented on modules/battery_manager/php/testprovisioner.class.inc
>              "SELECT b.id,
It is set via constructor property promotion. Line 43 is redundant because of the `protected` on line 39, so I removed it.

2024-12-13 21:17 UTC, driusan commented on modules/battery_manager/test/BatteryManagerTest.php
> -            '2 rows'
That's a good idea. I'll try.

2025-01-23 15:51 UTC, driusan commented on php/libraries/TimePoint.class.inc
> +        return iterator_to_array($provisioner->execute($user));
I'm not sure why this thread isn't showing up as "outdated". I'm no longer changing the return type and the code no longer shows as changed in the diff..

2025-01-23 15:59 UTC, driusan commented
@skarya22 I believe I've done all your requested changes and rebased this.

2025-01-28 21:09 UTC, skarya22 approved these changes
LGTM!

2025-02-03 21:30 UTC, merged