[Login] Summary Statistics
aces/Loris pull request #9518
Opened 2024-12-20 19:01 UTC by skarya22

## Brief summary of changes

- Added a customizable summary of LORIS statistics to the Login page for guest users to see
- A new table was created that is populated with the counts of pinned dataquery queries, and separated by project
- This table is read by the login module for projects with `showSummaryOnLogin` as true in the Project database table.
- If no data is populated, then the summary is not shown on the login page
- Data is populated by the new tool: `tools/update_login_summary_statistics.php`. It must be run for the data in the summary to be updated.
- Some queries are not necessarily possible in the DQT, so in-order to keep it customizable for projects, I added the ability to add SQL files to a folder in project/tools/Login_Summary_Statistics that can be added to the summary list.
<img width="641" alt="image" src="https://github.com/user-attachments/assets/50bdbb2e-0c3e-4060-ab76-ec500720026e" />

#### Testing instructions (if applicable)

1. Run the patch and the script, then open the login page and see that the page is unchanged
2. Login as admin, and go to the dataquery module. Create a query that includes the column Project. Run the query then go back to the dataquery homepage and pin the query to the login page. Give it a name, and leave out the 's' for plural (for example, `Male Participant` instead of `Male Participants`).
3. Run the script, then logout and see that the summary appears with a dropdown of all projects. When you select a different project, the count should change.
4. Change a project to `showSummaryOnLogin` = FALSE in the Project SQL table.
5. Re-run the script and note that the project is no longer in the dropdown, and the 'All Projects' count has decreased.
6. Try creating a new query that you only want to show for one project. To do this, create the query, including the Project column, then add a filter for Project = 'Pumpernickel'. Pin the project as before.
7. Run the script, and open the login page. See that the query is not included in the All Projects section, nor in other projects, and is only shown in Pumpernickel.
8. Now, try adding a query such as this to `project/tools/Login_Summary_Statistics` and see that it is now populated with Site.
[Site.txt](https://github.com/user-attachments/files/18214352/Site.txt)

[CCNA OVERRIDE PR ](https://github.com/aces/CCNA/pull/7416)

2024-12-20 19:12 UTC, skarya22 commented
The configuration for the summary statistics is currently done in two ways:
1. Pin a query from the datadict module to the Login Page
2. Add an SQL query to the `project/tools/Login_Summary_statistics` folder.

I had really liked the datadict integration, but after finishing I tried to test out some queries that we have on CCNA and realized they weren't possible. For instance, getting the distinct amount of sites with sessions for each project. I then added the ability to add SQL patches, which is a lot more simple. 

This PR needs discussion on whether I should just stick with the SQL files, or also keep the ability to pin queries from the DQT before I continue work on this.

2025-01-03 14:14 UTC, kongtiaowang commented on SQL/0000-00-00-schema.sql
> +    `showSummaryOnLogin` BOOLEAN DEFAULT TRUE;
`showSummaryOnLogin` BOOLEAN DEFAULT TRUE,

2025-01-03 14:31 UTC, skarya22 commented on SQL/0000-00-00-schema.sql
> +    `showSummaryOnLogin` BOOLEAN DEFAULT TRUE;
oh shoot - thanks!

2025-01-03 14:35 UTC, skarya22 commented on SQL/0000-00-00-schema.sql
> +    `showSummaryOnLogin` BOOLEAN DEFAULT TRUE;
Will fix if we discuss and decide to keep the pinning integration with DQT, otherwise this will be reverted

2025-01-07 16:18 UTC, skarya22 commented
From loris meeting Jan 7:
- Create a list of all the generalized statistics for LORIS core and ask each project to confirm that the values are correct for what they want
- Create a way to export data / download / script to export?
- Keep both implementatinons

2025-01-14 20:13 UTC, skarya22 commented on modules/configuration/php/configuration.class.inc
> +        $this->tpl_data['shared_queries'] = $user_starred_queries;
Can be removed

2025-01-15 19:57 UTC, skarya22 commented on SQL/New_patches/2024-12-18-Login_statistics.sql
> +    Value INT
```
    Order INT,
    PRIMARY KEY (Title, Project)
```

2025-01-15 19:57 UTC, skarya22 commented on tools/update_login_summary_statistics.php
> +
$order = 0;

2025-01-15 19:58 UTC, skarya22 commented on tools/update_login_summary_statistics.php
> +    }
$order++;

2025-01-15 19:58 UTC, skarya22 commented on tools/update_login_summary_statistics.php
> +                'value'   => $value
'Order' => $order,

2025-01-15 19:58 UTC, skarya22 commented on tools/update_login_summary_statistics.php
> +        );
$order++;

2025-01-15 20:22 UTC, skarya22 commented on tools/update_login_summary_statistics.php
> +        $queryName = explode("_", $queryName)[1];
$queryOrder = explode("_", $queryName)[0];
$queryToOrder[$queryName] = $queryOrder;

2025-01-15 20:22 UTC, skarya22 commented on tools/update_login_summary_statistics.php
> +
$queryToOrder = [];

2025-02-05 15:37 UTC, GeorgeMurad approved these changes
LGTM

2025-02-07 16:26 UTC, driusan commented on modules/login/jsx/summaryStatistics.js
> +                  {statistic.Value.toLocaleString('fr-CA')}{' '}
What is this hardcoded fr-CA for?

2025-02-07 16:27 UTC, driusan commented on modules/login/jsx/summaryStatistics.js
> +class SummaryStatistics extends Component {
I'm not going to block over it but I don't think it's a good idea to be making new class based components.

2025-02-07 16:29 UTC, driusan commented on SQL/New_patches/2024-12-18-Login_statistics.sql
> +DROP TABLE IF EXISTS Login_Summary_Statistics;
Don't drop tables in release patches. If something needs to be dropped (doesn't seem to be since it's created below), it should go in a cleanup patch.

2025-02-07 16:29 UTC, driusan commented on SQL/New_patches/2024-12-18-Login_statistics.sql
> +UPDATE Project SET showSummaryOnLogin = FALSE WHERE Name = 'DCP';
What is this?

2025-02-07 16:30 UTC, driusan requested changes
see comments

2025-02-07 20:16 UTC, skarya22 commented on SQL/New_patches/2024-12-18-Login_statistics.sql
> +UPDATE Project SET showSummaryOnLogin = FALSE WHERE Name = 'DCP';
the show `showSummaryOnLogin` column is for projects to be able to opt-out from being displayed on the login page, and then DCP is added as an example of how to do that in raisinbread

2025-02-07 20:17 UTC, skarya22 commented on modules/login/jsx/summaryStatistics.js
> +class SummaryStatistics extends Component {
What is the preferred alternative?

2025-02-07 20:17 UTC, skarya22 commented on modules/login/jsx/summaryStatistics.js
> +                  {statistic.Value.toLocaleString('fr-CA')}{' '}
This is for showing numbers as: `100 000` instead of `100000`

2025-02-12 19:21 UTC, driusan commented on SQL/New_patches/2024-12-18-Login_statistics.sql
> +UPDATE Project SET showSummaryOnLogin = FALSE WHERE Name = 'DCP';
But this patch is going to the release patch, not raisinbread. Can you remove this RB specific line?

2025-02-12 21:30 UTC, merged